### ISSUE TITLE
Calls API when calling to Number properly handle '+' sign which is not url encoded

### ISSUE THREAD

**Issue by gvagenas** [RestComm/Restcomm-Connect#1039]
If create call using Calls API to Number with '+' sign which is not url encoded (%2B) Restcomm should try to mitigate the issue and handle any exceptions.

**Comment by gvagenas** [comment]
The '+' sign turns to space and SipFactory fails to create SIP URI.

20:27:58,495 ERROR [org.mobicents.servlet.sip.message.SipFactoryImpl] (RestComm-akka.actor.default-dispatcher-4) couldn't parse the SipURI from USER[ 302123456789] HOST[sip.nexmo.com]: java.text.ParseException: sip: 302123456789@sip.nexmo.com: Missing host name
        at gov.nist.javax.sip.address.AddressFactoryImpl.createSipURI(AddressFactoryImpl.java:173) [jain-sip-ri-1.2.277.jar:1.2.277]
        at org.mobicents.servlet.sip.message.SipFactoryImpl.createSipURI(SipFactoryImpl.java:520)
        at org.mobicents.servlet.sip.message.SipFactoryFacade.createSipURI(SipFactoryFacade.java:195)
        at org.mobicents.servlet.restcomm.telephony.CallManager.outboundToPstn(CallManager.java:947) [restcomm.telephony-7.7.0-SNAPSHOT.jar:]
        at org.mobicents.servlet.restcomm.telephony.CallManager.outbound(CallManager.java:844) [restcomm.telephony-7.7.0-SNAPSHOT.jar:]
        at org.mobicents.servlet.restcomm.telephony.CallManager.onReceive(CallManager.java:649) [restcomm.telephony-7.7.0-SNAPSHOT.jar:]
        at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:159) [akka-actor_2.10-2.1.2.jar:]
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:425) [akka-actor_2.10-2.1.2.jar:]
        at akka.actor.ActorCell.invoke(ActorCell.scala:386) [akka-actor_2.10-2.1.2.jar:]
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:230) [akka-actor_2.10-2.1.2.jar:]
        at akka.dispatch.Mailbox.run(Mailbox.scala:212) [akka-actor_2.10-2.1.2.jar:]
        at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:506) [akka-actor_2.10-2.1.2.jar:]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:262) [scala-library-2.10.1.jar:]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:975) [scala-library-2.10.1.jar:]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1478) [scala-library-2.10.1.jar:]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104) [scala-library-2.10.1.jar:]

20:27:58,498 ERROR [org.mobicents.servlet.restcomm.telephony.CallManager] (RestComm-akka.actor.default-dispatcher-3) Could not create SIP URI user =  302123456789 host = sip.nexmo.com: java.lang.IllegalArgumentException: Could not create SIP URI user =  302123456789 host = sip.nexmo.com
        at org.mobicents.servlet.sip.message.SipFactoryImpl.createSipURI(SipFactoryImpl.java:525)
        at org.mobicents.servlet.sip.message.SipFactoryFacade.createSipURI(SipFactoryFacade.java:195)
        at org.mobicents.servlet.restcomm.telephony.CallManager.outboundToPstn(CallManager.java:947) [restcomm.telephony-7.7.0-SNAPSHOT.jar:]
        at org.mobicents.servlet.restcomm.telephony.CallManager.outbound(CallManager.java:844) [restcomm.telephony-7.7.0-SNAPSHOT.jar:]
        at org.mobicents.servlet.restcomm.telephony.CallManager.onReceive(CallManager.java:649) [restcomm.telephony-7.7.0-SNAPSHOT.jar:]
        at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:159) [akka-actor_2.10-2.1.2.jar:]
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:425) [akka-actor_2.10-2.1.2.jar:]
        at akka.actor.ActorCell.invoke(ActorCell.scala:386) [akka-actor_2.10-2.1.2.jar:]
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:230) [akka-actor_2.10-2.1.2.jar:]
        at akka.dispatch.Mailbox.run(Mailbox.scala:212) [akka-actor_2.10-2.1.2.jar:]
        at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:506) [akka-actor_2.10-2.1.2.jar:]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:262) [scala-library-2.10.1.jar:]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:975) [scala-library-2.10.1.jar:]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1478) [scala-library-2.10.1.jar:]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104) [scala-library-2.10.1.jar:]
