### ISSUE TITLE
NPE on Call Cancel

### ISSUE THREAD

**Issue by deruelle** [RestComm/Restcomm-Connect#1128]
10:56:27,764 INFO  [org.mobicents.servlet.restcomm.telephony.Call] (RestComm-akka.actor.default-dispatcher-733) Got CANCEL for Call, from: sip:Y@X:5180 to: sip:Z@XX:5080 state: initializing
10:56:27,764 ERROR [org.mobicents.servlet.restcomm.telephony.Call] (RestComm-akka.actor.default-dispatcher-733) java.lang.NullPointerException: org.mobicents.servlet.restcomm.fsm.TransitionFailedException: java.lang.NullPointerException
	at org.mobicents.servlet.restcomm.fsm.FiniteStateMachine.transition(FiniteStateMachine.java:102) [restcomm.commons-7.6.0.873.jar:]
	at org.mobicents.servlet.restcomm.telephony.Call.onCancel(Call.java:1242) [restcomm.telephony-7.6.0.873.jar:]
	at org.mobicents.servlet.restcomm.telephony.Call.onReceive(Call.java:403) [restcomm.telephony-7.6.0.873.jar:]
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:159) [akka-actor_2.10-2.1.2.jar:]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:425) [akka-actor_2.10-2.1.2.jar:]
	at akka.actor.ActorCell.invoke(ActorCell.scala:386) [akka-actor_2.10-2.1.2.jar:]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:230) [akka-actor_2.10-2.1.2.jar:]
	at akka.dispatch.Mailbox.run(Mailbox.scala:212) [akka-actor_2.10-2.1.2.jar:]
	at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:506) [akka-actor_2.10-2.1.2.jar:]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:262) [scala-library-2.10.1.jar:]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:975) [scala-library-2.10.1.jar:]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1478) [scala-library-2.10.1.jar:]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104) [scala-library-2.10.1.jar:]
Caused by: java.lang.NullPointerException
	at org.mobicents.servlet.restcomm.telephony.Call$Canceling.execute(Call.java:702) [restcomm.telephony-7.6.0.873.jar:]
	at org.mobicents.servlet.restcomm.fsm.FiniteStateMachine.transition(FiniteStateMachine.java:100) [restcomm.commons-7.6.0.873.jar:]
	... 12 more

**Comment by gvagenas** [comment]
@deruelle the line for 
```
Caused by: java.lang.NullPointerException
    at org.mobicents.servlet.restcomm.telephony.Call$Canceling.execute(Call.java:702) [restcomm.telephony-7.6.0.873.jar:]
```
is 
```
final SipServletRequest cancel = invite.createCancel();
```
Looks like the Invite at this point is null, can you think of any reason from SipServlet point of view that the invite is NULL at this point ?

George

**Comment by deruelle** [comment]
link to the code ? where do you get the invite from ?

**Comment by gvagenas** [comment]
https://github.com/RestComm/Restcomm-Connect/blob/5de0933b5e96cfbd32d3b05a1adeb3d357d06ae7/restcomm/restcomm.telephony/src/main/java/org/mobicents/servlet/restcomm/telephony/Call.java#L702

This is an outgoing call so invite is created at 
https://github.com/RestComm/Restcomm-Connect/blob/5de0933b5e96cfbd32d3b05a1adeb3d357d06ae7/restcomm/restcomm.telephony/src/main/java/org/mobicents/servlet/restcomm/telephony/Call.java#L595
or 
https://github.com/RestComm/Restcomm-Connect/blob/5de0933b5e96cfbd32d3b05a1adeb3d357d06ae7/restcomm/restcomm.telephony/src/main/java/org/mobicents/servlet/restcomm/telephony/Call.java#L597

**Comment by gvagenas** [comment]
SipSerlvets for that build (Restcomm 7.6.0.873) was SipServlets 3.1.691

**Comment by deruelle** [comment]
but the invite ref is clearly null here, we don't even go into SIP Servlets code as your invite object is null... when can the invite object be nullified at app level ?

**Comment by gvagenas** [comment]
Restcomm will not nullify the invite at any point. Restcomm will cleanup and destroy Call actor (and MS resources) and will let container to clean INVITE objects

**Comment by deruelle** [comment]
if the invite was not null the exception would happen in createCancel right ? here it seems to be happening really on the invite object. The container cannot nullify the invite at app level as it doesn't know about the app or how it store the ref to invite. Even if the container cleans the INVITE, the app will still hold a reference to it that would be non null.

**Comment by gvagenas** [comment]
@deruelle agree on you that if the invite was not null the exception would be in the createCancel but the invite cannot be null at this point and Call actor doesn't nullify the invite at any point, this is the strange part here. 
In any case, I can surround the createCancel method in a try/catch and log and cleanup so logging will help to spot the issue

**Comment by deruelle** [comment]
let's try that and provide a patch to see what more we can gather. Put enough logging there so we know about the Actor state as well in case it can be a race condition on the Actor cleanup too.

**Comment by gvagenas** [comment]
after properly guard code for the race condition the issue has been tested and cannot be reproduced
