### ISSUE TITLE
Handle SipServlets race condition where WSS outbound interface is null.

### ISSUE THREAD

**Issue by gvagenas** [RestComm/Restcomm-Connect#1191]
It can happen that SipServlets startup with no exceptions but the WSS outbound interface is NULL even though configuration is fine.
When this happen, if Restcomm will try to dial a WebRTC client over WSS the following exception will occur:

```
00:42:11,388 INFO  [org.mobicents.servlet.sip.core.session.SipApplicationSessionImpl] (RestComm_sip_standard_sas_timer_service) The following sip application session 827656f8;RestComm has been invalidated
00:42:11,391 ERROR [org.mobicents.servlet.restcomm.telephony.CallManager] (RestComm-akka.actor.default-dispatcher-30) null: java.lang.NullPointerException
        at org.mobicents.servlet.restcomm.telephony.CallManager.outboundToClient(CallManager.java:1006) [restcomm.telephony-7.8.0-SNAPSHOT.jar:]
        at org.mobicents.servlet.restcomm.telephony.CallManager.outbound(CallManager.java:938) [restcomm.telephony-7.8.0-SNAPSHOT.jar:]
        at org.mobicents.servlet.restcomm.telephony.CallManager.onReceive(CallManager.java:725) [restcomm.telephony-7.8.0-SNAPSHOT.jar:]
        at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:159) [akka-actor_2.10-2.1.2.jar:]
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:425) [akka-actor_2.10-2.1.2.jar:]
        at akka.actor.ActorCell.invoke(ActorCell.scala:386) [akka-actor_2.10-2.1.2.jar:]
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:230) [akka-actor_2.10-2.1.2.jar:]
        at akka.dispatch.Mailbox.run(Mailbox.scala:212) [akka-actor_2.10-2.1.2.jar:]
        at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:506) [akka-actor_2.10-2.1.2.jar:]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:262) [scala-library-2.10.1.jar:]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:975) [scala-library-2.10.1.jar:]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1478) [scala-library-2.10.1.jar:]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104) [scala-library-2.10.1.jar:]
```

At this point the outbound interfaces that are available from the container are:

1. sip:192.168.1.151:5082;transport=ws
2. sip:192.168.1.151:5080;transport=tcp
3. sip:192.168.1.151:5080;transport=udp

After Restcomm (container) restart the WSS interface is available and there is no exception.

**Comment by gvagenas** [comment]
Part of the standalone-sip.xml:

```
        <subsystem xmlns="urn:org.mobicents:sip-servlets-as7:1.0" application-router="configuration/dars/mobicents-dar.properties" stack-properties="configuration/mss-sip-stack.properties" path-name="org.mobicents.ext" app-dispatcher-class="org.mobicents.servlet.sip.core.SipApplicationDispatcherImpl" concurrency-control-mode="SipApplicationSession" congestion-control-interval="-1" gather-statistics="true">
            <connector name="sip-udp" protocol="SIP/2.0" scheme="sip" socket-binding="sip-udp" use-static-address="true" static-server-address="192.168.1.151" static-server-port="5080"/>
            <connector name="sip-tcp" protocol="SIP/2.0" scheme="sip" socket-binding="sip-tcp" use-static-address="true" static-server-address="192.168.1.151" static-server-port="5080"/>
            <connector name="sip-tls" protocol="SIP/2.0" scheme="sip" socket-binding="sip-tls" use-static-address="true" static-server-address="192.168.1.151" static-server-port="5081"/>
            <connector name="sip-ws" protocol="SIP/2.0" scheme="sip" socket-binding="sip-ws" use-static-address="true" static-server-address="192.168.1.151" static-server-port="5082"/>
             <connector name="sip-wss" protocol="SIP/2.0" scheme="sip" socket-binding="sip-wss" use-static-address="true" static-server-address="192.168.1.151" static-server-port="5083"/>
        </subsystem>
    </profile>
    <interfaces>
        <interface name="management">
            <inet-address value="${jboss.bind.address.management:127.0.0.1}"/>
        </interface>
        <interface name="public">
            <inet-address value="${jboss.bind.address:127.0.0.1}"/>
        </interface>
        <!-- TODO - only show this if the jacorb subsystem is added  -->
        <interface name="unsecure">
            <!--
              ~  Used for IIOP sockets in the standard configuration.
              ~                  To secure JacORB you need to setup SSL 
              -->
            <inet-address value="${jboss.bind.address.unsecure:127.0.0.1}"/>
        </interface>
    </interfaces>
    <socket-binding-group name="standard-sockets" default-interface="public" port-offset="${jboss.socket.binding.port-offset:0}">
        <socket-binding name="management-native" interface="management" port="${jboss.management.native.port:9999}"/>
        <socket-binding name="management-http" interface="management" port="${jboss.management.http.port:9990}"/>
        <socket-binding name="management-https" interface="management" port="${jboss.management.https.port:9443}"/>
        <socket-binding name="ajp" port="8009"/>
        <socket-binding name="http" port="8080"/>
        <socket-binding name="https" port="8443"/>
        <socket-binding name="sip-udp" port="5080"/>
        <socket-binding name="sip-tcp" port="5080"/>
        <socket-binding name="sip-tls" port="5081"/>
        <socket-binding name="sip-ws" port="5082"/>
        <socket-binding name="sip-wss" port="5083"/>
        <socket-binding name="remoting" port="4447"/>
        <socket-binding name="txn-recovery-environment" port="4712"/>
        <socket-binding name="txn-status-manager" port="4713"/>
        <outbound-socket-binding name="mail-smtp">
            <remote-destination host="localhost" port="25"/>
        </outbound-socket-binding>
```
