### ISSUE TITLE
NullPointerException for USSD Pull 

### ISSUE THREAD

**Issue by loayking** [RestComm/Restcomm-Connect#1206]
when i dial the USSD short code the request come to RestComm but sometimes  show this error
11:42:54,881 INFO [org.mobicents.servlet.restcomm.util.UriUtils] (RestComm-akka.actor.default-dispatcher-3) Jboss Http Connector: http://10.50.185.7:10010
11:42:54,887 ERROR [org.mobicents.servlet.restcomm.ussd.telephony.UssdCallManager] (RestComm-akka.actor.default-dispatcher-4) null: java.lang.NullPointerException
at org.mobicents.servlet.restcomm.util.UriUtils.resolve(UriUtils.java:55) [restcomm.commons-7.7.0.1295.jar:]
at org.mobicents.servlet.restcomm.util.UriUtils.resolve(UriUtils.java:164) [restcomm.commons-7.7.0.1295.jar:]
at org.mobicents.servlet.restcomm.ussd.telephony.UssdCallManager.redirectToHostedVoiceApp(UssdCallManager.java:231) [restcomm.ussd-7.7.0.1295.jar:]
at org.mobicents.servlet.restcomm.ussd.telephony.UssdCallManager.invite(UssdCallManager.java:187) [restcomm.ussd-7.7.0.1295.jar:]
at org.mobicents.servlet.restcomm.ussd.telephony.UssdCallManager.onReceive(UssdCallManager.java:149) [restcomm.ussd-7.7.0.1295.jar:]
at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:159) [akka-actor_2.10-2.1.2.jar:]
at akka.actor.ActorCell.receiveMessage(ActorCell.scala:425) [akka-actor_2.10-2.1.2.jar:]
at akka.actor.ActorCell.invoke(ActorCell.scala:386) [akka-actor_2.10-2.1.2.jar:]
at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:230) [akka-actor_2.10-2.1.2.jar:]
at akka.dispatch.Mailbox.run(Mailbox.scala:212) [akka-actor_2.10-2.1.2.jar:]
at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:506) [akka-actor_2.10-2.1.2.jar:]
at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:262) [scala-library-2.10.1.jar:]
at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:975) [scala-library-2.10.1.jar:]
at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1478) [scala-library-2.10.1.jar:]
at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104) [scala-library-2.10.1.jar:]

**Comment by gvagenas** [comment]
@loayking Since Restcomm 7.6.0 the USSD numbers should use the USSD Url and not the Voice URL. From the NPE you have here, I assume that the number you use here is using VoiceURL. You should instead configure your application at the USSD url. This is issue https://github.com/RestComm/Restcomm-Connect/issues/805

Let me know if that helps so I can close the issue

**Comment by deruelle** [comment]
We shouldn't bomb with NPE still

**Comment by gvagenas** [comment]
@deruelle agree, I plan to properly handle the exception at this point

**Comment by loayking** [comment]
@gvagenas yes you are right it is working fine now
