### ISSUE TITLE
Activating LB on Latest version causes server FATAL error

### ISSUE THREAD

**Issue by croufay** [RestComm/Restcomm-Connect#1423]
07:25:43,451 INFO  [org.jboss.as] (MSC service thread 1-7) JBAS015899: JBoss AS 7.2.0.Final "Janus" starting
07:25:44,444 ERROR [org.jboss.as.server] (Controller Boot Thread) JBAS015956: Caught exception during boot: org.jboss.as.controller.persistence.ConfigurationPersistenceException: JBAS014676: Failed to parse configuration
	at org.jboss.as.controller.persistence.XmlConfigurationPersister.load(XmlConfigurationPersister.java:141) [jboss-as-controller-7.2.0.Final.jar:7.2.0.Final]
	at org.jboss.as.server.ServerService.boot(ServerService.java:308) [jboss-as-server-7.2.0.Final.jar:7.2.0.Final]
	at org.jboss.as.controller.AbstractControllerService$1.run(AbstractControllerService.java:188) [jboss-as-controller-7.2.0.Final.jar:7.2.0.Final]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_95]
Caused by: java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) [rt.jar:1.7.0_95]
	at java.lang.Integer.parseInt(Integer.java:504) [rt.jar:1.7.0_95]
	at java.lang.Integer.parseInt(Integer.java:527) [rt.jar:1.7.0_95]
	at org.jboss.dmr.StringModelValue.asInt(StringModelValue.java:139) [jboss-dmr-1.1.6.Final.jar:1.1.6.Final]
	at org.jboss.dmr.ModelNode.asInt(ModelNode.java:226) [jboss-dmr-1.1.6.Final.jar:1.1.6.Final]
	at org.jboss.as.controller.SimpleAttributeDefinition.parse(SimpleAttributeDefinition.java:311) [jboss-as-controller-7.2.0.Final.jar:7.2.0.Final]
	at org.jboss.as.controller.SimpleAttributeDefinition.parse(SimpleAttributeDefinition.java:159) [jboss-as-controller-7.2.0.Final.jar:7.2.0.Final]
	at org.jboss.as.controller.SimpleAttributeDefinition.parseAndSetParameter(SimpleAttributeDefinition.java:214) [jboss-as-controller-7.2.0.Final.jar:7.2.0.Final]
	at org.mobicents.as7.SipSubsystemParser.parseConnector(SipSubsystemParser.java:221)
	at org.mobicents.as7.SipSubsystemParser.readElement(SipSubsystemParser.java:172)
	at org.mobicents.as7.SipSubsystemParser.readElement(SipSubsystemParser.java:57)
	at org.jboss.staxmapper.XMLMapperImpl.processNested(XMLMapperImpl.java:110) [staxmapper-1.1.0.Final.jar:1.1.0.Final]
	at org.jboss.staxmapper.XMLExtendedStreamReaderImpl.handleAny(XMLExtendedStreamReaderImpl.java:69) [staxmapper-1.1.0.Final.jar:1.1.0.Final]
	at org.jboss.as.server.parsing.StandaloneXml.parseServerProfile(StandaloneXml.java:1028) [jboss-as-server-7.2.0.Final.jar:7.2.0.Final]
	at org.jboss.as.server.parsing.StandaloneXml.readServerElement_1_4(StandaloneXml.java:449) [jboss-as-server-7.2.0.Final.jar:7.2.0.Final]
	at org.jboss.as.server.parsing.StandaloneXml.readElement(StandaloneXml.java:136) [jboss-as-server-7.2.0.Final.jar:7.2.0.Final]
	at org.jboss.as.server.parsing.StandaloneXml.readElement(StandaloneXml.java:103) [jboss-as-server-7.2.0.Final.jar:7.2.0.Final]
	at org.jboss.staxmapper.XMLMapperImpl.processNested(XMLMapperImpl.java:110) [staxmapper-1.1.0.Final.jar:1.1.0.Final]
	at org.jboss.staxmapper.XMLMapperImpl.parseDocument(XMLMapperImpl.java:69) [staxmapper-1.1.0.Final.jar:1.1.0.Final]
	at org.jboss.as.controller.persistence.XmlConfigurationPersister.load(XmlConfigurationPersister.java:133) [jboss-as-controller-7.2.0.Final.jar:7.2.0.Final]
	... 3 more

07:25:44,452 FATAL [org.jboss.as.server] (Controller Boot Thread) JBAS015957: Server boot has failed in an unrecoverable manner; exiting. See previous messages for details.
07:25:44,472 INFO  [org.jboss.as] (MSC service thread 1-19) JBAS015950: JBoss AS 7.2.0.Final "Janus" stopped in 9ms

**Comment by croufay** [comment]
this like is missing in the advanced.conf file


LB_RMI_PORT='2000'          #The port used from RMI connection between RC and LB. Default is 2000.

This is what caused the FATAL error. Restcomm now starts after adding the above to the advanced.conf
