### ISSUE TITLE
BufferOverflowException in MediaGatway

### ISSUE THREAD

**Issue by maria-farooq** [RestComm/Restcomm-Connect#1472]
```
14:59:42,174 ERROR [org.mobicents.servlet.restcomm.mgcp.MediaGateway] (RestComm-akka.actor.default-dispatcher-169) null: java.nio.BufferOverflowException
    at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:357) [rt.jar:1.7.0_80]
    at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:336) [rt.jar:1.7.0_80]
    at sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:493) [rt.jar:1.7.0_80]
    at sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:462) [rt.jar:1.7.0_80]
    at org.mobicents.protocols.mgcp.stack.JainMgcpStackImpl.send(JainMgcpStackImpl.java:308) [mgcp-driver-4.1.0.59.556.jar:4.1.0.59.556]
    at org.mobicents.protocols.mgcp.handlers.TransactionHandler.send(TransactionHandler.java:490) [mgcp-driver-4.1.0.59.556.jar:4.1.0.59.556]
    at org.mobicents.protocols.mgcp.handlers.TransactionHandler.send(TransactionHandler.java:371) [mgcp-driver-4.1.0.59.556.jar:4.1.0.59.556]
    at org.mobicents.protocols.mgcp.stack.JainMgcpStackProviderImpl.sendMgcpEvents(JainMgcpStackProviderImpl.java:253) [mgcp-driver-4.1.0.59.556.jar:4.1.0.59.556]
    at org.mobicents.servlet.restcomm.mgcp.MediaGateway.send(MediaGateway.java:366) [restcomm.mgcp-8.0.0-SNAPSHOT.jar:]
    at org.mobicents.servlet.restcomm.mgcp.MediaGateway.onReceive(MediaGateway.java:346) [restcomm.mgcp-8.0.0-SNAPSHOT.jar:]
    at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:159) [akka-actor_2.10-2.1.2.jar:]
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:425) [akka-actor_2.10-2.1.2.jar:]
    at akka.actor.ActorCell.invoke(ActorCell.scala:386) [akka-actor_2.10-2.1.2.jar:]
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:230) [akka-actor_2.10-2.1.2.jar:]
    at akka.dispatch.Mailbox.run(Mailbox.scala:212) [akka-actor_2.10-2.1.2.jar:]
    at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:506) [akka-actor_2.10-2.1.2.jar:]
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:262) [scala-library-2.10.1.jar:]
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:975) [scala-library-2.10.1.jar:]
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1478) [scala-library-2.10.1.jar:]
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104) [scala-library-2.10.1.jar:]
14:59:42,176 INFO  [org.mobicents.servlet.restcomm.interpreter.VoiceInterpreter] (RestComm-akka.actor.default-dispatcher-169)  ********** VoiceInterpreter's akka://RestComm/user/$y Current State: acquiring conference info
```

more logs are attached at https://app.box.com/files/0/f/11576359008/1/f_97743503489
we need to investigate what causes this exception

**Comment by leftyb** [comment]
@hrosa logs from mgcp isseu:

https://app.box.com/files/0/f/11838508899/mgcp_problem_HA_RC03

**Comment by maria-farooq** [comment]
thanks @hrosa for providing patch release. http://ci.telestax.com/view/MediaServer/job/telscale-mediaserver-4.1.0.60/1/
its deployed on HA env. and so far we have not faced this issue  .
