### ISSUE TITLE
UserAgentManager should ping only registrations that belong to the current instance

### ISSUE THREAD

**Issue by gvagenas** [RestComm/Restcomm-Connect#1483]

**Comment by gvagenas** [comment]
Protect keepAlive method in the case where there are no registrations for the current instance, exception:

```
10:08:21,709 ERROR [org.restcomm.connect.telephony.ua.UserAgentManager] (RestComm-akka.actor.default-dispatcher-74) null: java.lang.NullPointerException
        at org.restcomm.connect.telephony.ua.UserAgentManager.keepAlive(UserAgentManager.java:226) [restcomm-connect.telephony-8.0.0.9.jar:8.0.0.9]
        at org.restcomm.connect.telephony.ua.UserAgentManager.onReceive(UserAgentManager.java:242) [restcomm-connect.telephony-8.0.0.9.jar:8.0.0.9]
        at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:159) [akka-actor_2.10-2.1.2.jar:]
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:425) [akka-actor_2.10-2.1.2.jar:]
        at akka.actor.ActorCell.invoke(ActorCell.scala:386) [akka-actor_2.10-2.1.2.jar:]
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:230) [akka-actor_2.10-2.1.2.jar:]
        at akka.dispatch.Mailbox.run(Mailbox.scala:212) [akka-actor_2.10-2.1.2.jar:]
        at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:506) [akka-actor_2.10-2.1.2.jar:]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:262) [scala-library-2.10.1.jar:]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:975) [scala-library-2.10.1.jar:]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1478) [scala-library-2.10.1.jar:]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104) [scala-library-2.10.1.jar:]
```
