### ISSUE TITLE
DB Error when sending SMS, if FROM too big.

### ISSUE THREAD

**Issue by leftyb** [RestComm/Restcomm-Connect#1642]
```12:27:37,016 ERROR [org.restcomm.connect.interpreter.VoiceInterpreter] (RestComm-akka.actor.default-dispatcher-387) org.apache.ibatis.exceptions.PersistenceException: RestCommException /
### Error updating database. Cause: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'sender' at row 1 RestCommException HACloud03/HACloudRC3
### The error may involve org.mobicents.servlet.sip.restcomm.dao.SmsMessagesDao.addSmsMessage-Inline RestCommException /
### The error occurred while setting parameters RestCommException /
### SQL: INSERT INTO restcomm_sms_messages (sid, date_created, date_updated, date_sent, account_sid, sender, recipient, body, status, direction, price, api_version, uri) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?); /
### Cause: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'sender' at row 1: org.restcomm.connect.commons.fsm.TransitionFailedException: org.apache.ibatis.exceptions.PersistenceException: RestCommException /
### Error updating database. Cause: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'sender' at row 1 RestCommException /
### The error may involve org.mobicents.servlet.sip.restcomm.dao.SmsMessagesDao.addSmsMessage-Inline RestCommException /
### The error occurred while setting parameters RestCommException /
### SQL: INSERT INTO restcomm_sms_messages (sid, date_created, date_updated, date_sent, account_sid, sender, recipient, body, status, direction, price, api_version, uri) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?); /
### Cause: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'sender' at row 1 /
at org.restcomm.connect.commons.fsm.FiniteStateMachine.transition(FiniteStateMachine.java:89) [restcomm-connect.commons-8.0.0.1084.jar:8.0.0.1084] /
at org.restcomm.connect.interpreter.VoiceInterpreter.onSmsServiceResponse(VoiceInterpreter.java:725) [restcomm-connect.interpreter-8.0.0.1084.jar:8.0.0.1084] /
at org.restcomm.connect.interpreter.VoiceInterpreter.onReceive(VoiceInterpreter.java:523) [restcomm-connect.interpreter-8.0.0.1084.jar:8.0.0.1084] /
at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:159) [akka-actor_2.10-2.1.2.jar:] /
at akka.actor.ActorCell.receiveMessage(ActorCell.scala:425) [akka-actor_2.10-2.1.2.jar:] /
at akka.actor.ActorCell.invoke(ActorCell.scala:386) [akka-actor_2.10-2.1.2.jar:] /
at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:230) [akka-actor_2.10-2.1.2.jar:] /
at akka.dispatch.Mailbox.run(Mailbox.scala:212) [akka-actor_2.10-2.1.2.jar:] /
at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:506) [akka-actor_2.10-2.1.2.jar:] /
at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:262) [scala-library-2.10.1.jar:] /
at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:975) [scala-library-2.10.1.jar:] /
at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1478) [scala-library-2.10.1.jar:] /
at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104) [scala-library-2.10.1.jar:] /
Caused by: org.apache.ibatis.exceptions.PersistenceException: RestCommException /
### Error updating database. Cause: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'sender' at row 1 RestCommException /
### The error may involve org.mobicents.servlet.sip.restcomm.dao.SmsMessagesDao.addSmsMessage-Inline RestCommException /
### The error occurred while setting parameters RestCommException /
### SQL: INSERT INTO restcomm_sms_messages (sid, date_created, date_updated, date_sent, account_sid, sender, recipient, body, status, direction, price, api_version, uri) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?); /
### Cause: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'sender' at row 1 /
at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:23) [mybatis-3.2.2.jar:3.2.2] RestCommException /
at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:150) [mybatis-3.2.2.jar:3.2.2] /
at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:137) [mybatis-3.2.2.jar:3.2.2] /
at org.restcomm.connect.dao.mybatis.MybatisSmsMessagesDao.addSmsMessage(MybatisSmsMessagesDao.java:69) [restcomm-connect.dao-8.0.0.1084.jar:8.0.0.1084] /
at org.restcomm.connect.interpreter.BaseVoiceInterpreter$SendingSms.execute(BaseVoiceInterpreter.java:2051) [restcomm-connect.interpreter-8.0.0.1084.jar:8.0.0.1084] /
at org.restcomm.connect.commons.fsm.FiniteStateMachine.transition(FiniteStateMachine.java:87) [rest...
Add Comment Coll```

From Jean:
the column size is probably too small, but also we shouldn't bomb.
we should return at API level a correct error, and do the check on size before pushing into DB.

**Comment by deruelle** [comment]
@gvagenas we should protect at the code level as well. What id someone uses more than 255 characters. This will blow up again. We should do a check at Java code and return a meaningful error for the outbound (HTTP API) and meaningful SIP or SMPP error for inbound
