### ISSUE TITLE
Moving call from Cancel to Failed is causing TransitionNotFoundException

### ISSUE THREAD

**Issue by maria-farooq** [RestComm/Restcomm-Connect#1844]
complete logs can be found at https://app.box.com/files/0/f/19655751438/call_fsm_exception
```
18:15:42,170 INFO  [org.restcomm.connect.monitoringservice.MonitoringService] (RestComm-akka.actor.default-dispatcher-2229) MonitoringService Processing Message: "org.restcomm.connect.telephony.api.GetLiveCalls sender : class akka.pattern.PromiseActorRef self is terminated: false
18:15:42,171 WARN  [org.restcomm.connect.http.client.Downloader] (RestComm-akka.actor.default-dispatcher-2229) Problem while trying to download RCML  WARNING arguments left: 1
18:15:42,171 INFO  [org.restcomm.connect.interpreter.VoiceInterpreter] (RestComm-akka.actor.default-dispatcher-2229)  ********** VoiceInterpreter's akka://RestComm/user/$ke Current State: downloading rcml
, Processing Message: org.restcomm.connect.http.client.DownloaderResponse
18:15:42,172 INFO  [org.restcomm.connect.telephony.Call] (RestComm-akka.actor.default-dispatcher-2229) ********** Call's akka://RestComm/user/$le Current State: "canceling direction: inbound
18:15:42,172 INFO  [org.restcomm.connect.telephony.Call] (RestComm-akka.actor.default-dispatcher-2229) ********** Call akka://RestComm/user/$le Processing Message: "org.restcomm.connect.telephony.api.CallFail sender : akka://RestComm/user/$ke
18:15:42,172 ERROR [org.restcomm.connect.telephony.Call] (RestComm-akka.actor.default-dispatcher-2229) No transition could be found from a(n) canceling state to a(n) failed state.: org.restcomm.connect.commons.fsm.TransitionNotFoundException: No transition could be found from a(n) canceling state to a(n) failed state.
	at org.restcomm.connect.commons.fsm.FiniteStateMachine.transition(FiniteStateMachine.java:60) [restcomm-connect.commons-8.1.0.1158.jar:8.1.0.1158]
	at org.restcomm.connect.telephony.Call.onReceive(Call.java:495) [restcomm-connect.telephony-8.1.0.1158.jar:8.1.0.1158]
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:159) [akka-actor_2.10-2.1.2.jar:]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:425) [akka-actor_2.10-2.1.2.jar:]
	at akka.actor.ActorCell.invoke(ActorCell.scala:386) [akka-actor_2.10-2.1.2.jar:]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:230) [akka-actor_2.10-2.1.2.jar:]
	at akka.dispatch.Mailbox.run(Mailbox.scala:212) [akka-actor_2.10-2.1.2.jar:]
	at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:506) [akka-actor_2.10-2.1.2.jar:]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:262) [scala-library-2.10.1.jar:]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:975) [scala-library-2.10.1.jar:]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1478) [scala-library-2.10.1.jar:]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104) [scala-library-2.10.1.jar:]
18:15:42,174 INFO  [org.restcomm.connect.telephony.Call] (RestComm-akka.actor.default-dispatcher-2229) Call actor at postStop, path: akka://RestComm/user/$le, direction: inbound, state: canceling, isTerminated: false, sender: Actor[akka://RestComm/user/$ke]
18:15:42,174 INFO  [org.restcomm.connect.telephony.Call] (RestComm-akka.actor.default-dispatcher-2229) Sent stop observing for call, from: sip:33155933340@185.43.128.28 to: sip:33974481541@cloud.restcomm.com:5060 direction: inbound to observer: akka://RestComm/user/$ke observer is terminated: false
18:15:42,174 INFO  [org.restcomm.connect.interpreter.VoiceInterpreter] (RestComm-akka.actor.default-dispatcher-2229)  ********** VoiceInterpreter's akka://RestComm/user/$ke Current State: downloading rcml
```

**Comment by maria-farooq** [comment]
duplicate #1830
