### ISSUE TITLE
invalid parameter cause exception in UAM

### ISSUE THREAD

**Issue by maria-farooq** [RestComm/Restcomm-Connect#1978]
```
11:38:38,563 INFO  [org.restcomm.connect.telephony.ua.UserAgentManager] (RestComm-akka.actor.default-dispatcher-511) Registration: sip:critz.chan%40telestax.com@cloud.restcomm.com expired. Will ping again.
11:38:38,563 ERROR [org.restcomm.connect.telephony.ua.UserAgentManager] (RestComm-akka.actor.default-dispatcher-511) Bad param sip:critz.chan@telestax.com@211.25.30.52:55263;transport=tcp: javax.servlet.sip.ServletParseException: Bad param sip:critz.chan@telestax.com@211.25.30.52:55263;transport=tcp
	at org.mobicents.servlet.sip.message.SipFactoryImpl.createURI(SipFactoryImpl.java:620)
	at org.mobicents.servlet.sip.message.SipFactoryFacade.createURI(SipFactoryFacade.java:202)
	at org.restcomm.connect.telephony.ua.UserAgentManager.ping(UserAgentManager.java:407) [restcomm-connect.telephony-8.1.0.1185.jar:8.1.0.1185]
	at org.restcomm.connect.telephony.ua.UserAgentManager.clean(UserAgentManager.java:181) [restcomm-connect.telephony-8.1.0.1185.jar:8.1.0.1185]
	at org.restcomm.connect.telephony.ua.UserAgentManager.onReceive(UserAgentManager.java:267) [restcomm-connect.telephony-8.1.0.1185.jar:8.1.0.1185]
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:159) [akka-actor_2.10-2.1.2.jar:]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:425) [akka-actor_2.10-2.1.2.jar:]
	at akka.actor.ActorCell.invoke(ActorCell.scala:386) [akka-actor_2.10-2.1.2.jar:]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:230) [akka-actor_2.10-2.1.2.jar:]
	at akka.dispatch.Mailbox.run(Mailbox.scala:212) [akka-actor_2.10-2.1.2.jar:]
	at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:506) [akka-actor_2.10-2.1.2.jar:]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:262) [scala-library-2.10.1.jar:]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:975) [scala-library-2.10.1.jar:]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1478) [scala-library-2.10.1.jar:]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104) [scala-library-2.10.1.jar:]
Caused by: java.text.ParseException: sip:critz.chan@telestax.com@211.25.30.52:55263;transport=tcp Illegal character in hostname:@
	at gov.nist.javax.sip.address.AddressFactoryImpl.createURI(AddressFactoryImpl.java:233) [jain-sip-ri-1.2.293.jar:1.2.293]
	at org.mobicents.servlet.sip.message.SipFactoryImpl.createURI(SipFactoryImpl.java:608)
	... 14 more
11:38:38,570 ERROR [org.restcomm.connect.commons.faulttolerance.RestcommSupervisor] (RestComm-akka.actor.default-dispatcher-511) Handling exception javax.servlet.sip.ServletParseException will resume
```

**Comment by gvagenas** [comment]
closed with PR #1980
