### ISSUE TITLE
USSD Push is broken using the API

### ISSUE THREAD

**Issue by croufay** [RestComm/Restcomm-Connect#2054]
When I try to run USSD PUSH  using the binary TelScale-Restcomm-JBoss-AS7-8.1.0.1502

I was try to create an example for a customer but there seem to be a bug 

 curl -X POST -H "application/json" http://ACae6e420f425248d6a26948c17a9e2acf:PWD@192.168.1.3:8080/restcomm/2012-04-24/Accounts/ACae6e420f425248d6a26948c17a9e2acf/UssdPush -d "From=Restcomm" -d "To=111111" -d "Url=http://192.168.1.3:8080/restcomm-rvd/services/apps/AP2f2e81e597af44e9a153b10c81427d87/controller"
<html><head><title>JBoss Web/7.2.0.Final - JBWEB000064: Error report</title><style></style> </head><body><h1>JBWEB000065: HTTP Status 500 - Internal Server Error</h1><HR size="1" noshade="noshade"><p><b>JBWEB000309: type</b> JBWEB000067: Status report</p><p><b>JBWEB000068: message</b> <u>Internal Server Error</u></p><p><b>JBWEB000069: description</b> <u>JBWEB000145: The server encountered an internal error that prevented it from fulfilling this request.</u></p><HR size="1" noshade="noshade"><h3>JBoss Web/7.2.0.Final</h3></body></html>

Error Log

2:30:35,960 INFO  [org.restcomm.connect.telephony.ua.UserAgentManager] (RestComm-akka.actor.default-dispatcher-39) UserAgentManager Processing Message: "akka.actor.ReceiveTimeout$ sender : class akka.actor.DeadLetterActorRef self is terminated: false
^[22:31:27,466 ERROR [org.mobicents.servlet.sip.message.SipFactoryImpl] (RestComm-akka.actor.default-dispatcher-39) couldn't parse the SipURI from USER[Restcomm] HOST[]: java.text.ParseException: sip:Restcomm@: Missing host name
        at gov.nist.javax.sip.address.AddressFactoryImpl.createSipURI(AddressFactoryImpl.java:173) [jain-sip-ri-1.2.293.jar:1.2.293]
        at org.mobicents.servlet.sip.message.SipFactoryImpl.createSipURI(SipFactoryImpl.java:593)
        at org.mobicents.servlet.sip.message.SipFactoryFacade.createSipURI(SipFactoryFacade.java:195)
        at org.restcomm.connect.ussd.telephony.UssdCallManager.outbound(UssdCallManager.java:278) [restcomm-connect.ussd-8.1.0.1205.jar:8.1.0.1205]
        at org.restcomm.connect.ussd.telephony.UssdCallManager.onReceive(UssdCallManager.java:161) [restcomm-connect.ussd-8.1.0.1205.jar:8.1.0.1205]
        at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:159) [akka-actor_2.10-2.1.2.jar:]
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:425) [akka-actor_2.10-2.1.2.jar:]
        at akka.actor.ActorCell.invoke(ActorCell.scala:386) [akka-actor_2.10-2.1.2.jar:]
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:230) [akka-actor_2.10-2.1.2.jar:]
        at akka.dispatch.Mailbox.run(Mailbox.scala:212) [akka-actor_2.10-2.1.2.jar:]
        at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:506) [akka-actor_2.10-2.1.2.jar:]
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:262) [scala-library-2.10.1.jar:]
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:975) [scala-library-2.10.1.jar:]
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1478) [scala-library-2.10.1.jar:]
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104) [scala-library-2.10.1.jar:]

**Comment by gvagenas** [comment]
Thanks @croufay , will check this

**Comment by croufay** [comment]
@gvagenas ,

I tested again by replacing the restcomm-connect.ussd-8.1.0.1205.jar with  the latest restcomm-connect.ussd-8.2.0-SNAPSHOT.jar and the USSD push worked.


`
curl -X POST -H "application/json" http://ACae6e420f425248d6a26948c172.168.1.3:8080/restcomm/2012-04-24/Accounts/ACae6e420f425248d6a26948c17a9e2acf/UssdPush -d "From=Restcomm" -d "To=111111" -d "Url=http://192.168.1.3:8080/restcomm-rvd/services/apps/AP2f2e81e597af44e9a153b10c81427d87/controller"
<RestcommResponse>
  <Call>
    <Sid>CAf53b383168244254aaac3a8c6574ab9c</Sid>
    <InstanceId>IDcd4a4fab9dfb4b5c9d7eaecd099fc119</InstanceId>
    <DateCreated>Thu, 13 Apr 2017 12:51:22 -0600</DateCreated>
    <DateUpdated>Thu, 13 Apr 2017 12:51:22 -0600</DateUpdated>
    <ParentCallSid/>
    <AccountSid>ACae6e420f425248d6a26948c17a9e2acf</AccountSid>
    <To>111111</To>
    <From>USSD REST API</From>
    <PhoneNumberSid/>
    <Status>QUEUED</Status>
    <StartTime/>
    <EndTime/>
    <Duration/>
    <Price>0.00</Price>
    <PriceUnit>USD</PriceUnit>
    <Direction>outbound-api</Direction>
    <AnsweredBy/>
    <ApiVersion>2012-04-24</ApiVersion>
    <ForwardedFrom/>
    <CallerName/>
    <Uri>/2012-04-24/Accounts/ACae6e420f425248d6a26948c17a9e2acf/Calls/CAf53b383168244254aaac3a8c6574ab9c</Uri>
    <SubresourceUris>
      <Notifications>/2012-04-24/Accounts/ACae6e420f425248d6a26948c17a9e2acf/Calls/CAf53b383168244254aaac3a8c6574ab9c/Notifications</Notifications>
      <Recordings>/2012-04-24/Accounts/ACae6e420f425248d6a26948c17a9e2acf/Calls/CAf53b383168244254aaac3a8c6574ab9c/Recordings</Recordings>
    </SubresourceUris>
    <Ring__duration/>
  </Call>
`
Changes made in the past week must have fixed the NullPointer issue, I will test again and if all goes well, replace the jar file in our next upgrade window with the customer
