### ISSUE TITLE
Fail fast when Supervisor endpoint cannot get the metrics from MonitoringService

### ISSUE THREAD

**Issue by gvagenas** [RestComm/Restcomm-Connect#2121]

**Comment by jaimecasero** [comment]
from therad dump i think this was related:
"http-/10.0.0.5:443-2" daemon prio=10 tid=0x0000000001a23800 nid=0x4c2 runnable [0x00007ff367a9f000]
  java.lang.Thread.State: RUNNABLE
    at java.net.SocketInputStream.socketRead0(Native Method)
    at java.net.SocketInputStream.read(SocketInputStream.java:152)
    at java.net.SocketInputStream.read(SocketInputStream.java:122)
    at sun.security.ssl.InputRecord.readFully(InputRecord.java:442)
    at sun.security.ssl.InputRecord.read(InputRecord.java:480)
    at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:934)
    - locked <0x00000006665ad630> (a java.lang.Object)
    at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:891)
    at sun.security.ssl.AppInputStream.read(AppInputStream.java:102)
    - locked <0x00000006666a7b40> (a sun.security.ssl.AppInputStream)
    at org.apache.coyote.http11.InternalInputBuffer.fill(InternalInputBuffer.java:721)
    at org.apache.coyote.http11.InternalInputBuffer.parseRequestLine(InternalInputBuffer.java:359)
    at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:821)
    at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:653)
    at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:920)
    at java.lang.Thread.run(Thread.java:745)

**Comment by gvagenas** [comment]
Thanks @jaimecasero

**Comment by gvagenas** [comment]
The patch will reduce the timeout for the MonitoringService ask metrics operation, so if there is an issue, it will fail fast and return an exception instead of waiting long time for a response.

Proper fix for this issue should be:
1. Upgrade to Jersey 2.x and use AsyncResponse (https://jersey.java.net/documentation/latest/async.html)
2. Use Scala Future onSuccess callback (http://doc.akka.io/docs/akka/2.1.4/java/futures.html) to get the MonitoringServiceResponse without blocking and then return the response
