### ISSUE TITLE
Test Case failing for org.restcomm.connect.dao.mybatis.CallDetailRecordsDaoTest

### ISSUE THREAD

**Issue by arslan70** [RestComm/Restcomm-Connect#2252]
using the master branch restcomm.dao is failing to compile due to the mentioned test case failing

**Output**
testReadByEndTime(org.restcomm.connect.dao.mybatis.CallDetailRecordsDaoTest)  Time elapsed: 0.146 sec  <<< FAILURE!
java.lang.AssertionError: null
        at org.junit.Assert.fail(Assert.java:92)
        at org.junit.Assert.assertTrue(Assert.java:43)
        at org.junit.Assert.assertTrue(Assert.java:54)
        at org.restcomm.connect.dao.mybatis.CallDetailRecordsDaoTest.testReadByEndTime(CallDetailRecordsDaoTest.java:370)

**Code:**
`Line: 370         assertTrue(cdrs.getCallDetailRecordsByEndTime(now).size() == 1);`

**Comment by arslan70** [comment]
Apparently there are more CDRs in the testing script. Changing below

` Line: 370 assertTrue(cdrs.getCallDetailRecordsByEndTime(now).size() == 1);`

to 

`assertTrue(cdrs.getCallDetailRecordsByEndTime(new DateTime(2017, 6, 20, 3, 1)).size() > 1);`

Makes the test cases pass

**Comment by arslan70** [comment]
Apparently there are more CDRs in the testing script. Changing below

` Line: 370 assertTrue(cdrs.getCallDetailRecordsByEndTime(now).size() == 1);`

to 

`assertTrue(cdrs.getCallDetailRecordsByEndTime(new DateTime(2017, 6, 20, 3, 1)).size() > 1);`

Makes the test cases pass


I wonder how these 2 cases were getting passed before

`assertTrue(cdrs.getCallDetailRecordsByEndTime(now).size() == 1);`
`assertTrue(cdrs.getCallDetailRecordsByStarTimeAndEndTime(now).size() == 1);`

cdrs.getCallDetailRecordsByStarTimeAndEndTime uses mybatis method getCallDetailRecordsByStarTimeAndEndTime

Which is not defined in any mybatis xml file. @maria-farooq can you take a look please?

**Comment by arslan70** [comment]
Sigh! Still no luck with the master branch

![image](https://user-images.githubusercontent.com/1875949/27436577-2159c038-5779-11e7-8017-13c7dc7f5783.png)

I can do a pull request to fix this if this isn't something happening to me alone.

**Comment by maria-farooq** [comment]
related to https://github.com/RestComm/Restcomm-Connect/pull/2201

**Comment by maria-farooq** [comment]
Hi @arslan70 

Really sorry for the delay in response.
this task and [PR](https://github.com/RestComm/Restcomm-Connect/pull/2201) is planned for @gvagenas to review in next week.

we are really grateful for your efforts here.

Regards
Maria

**Comment by arslan70** [comment]
Thanks Maria, much appreciated.
