### ISSUE TITLE
When an instant message is received which is empty, exception occurs

### ISSUE THREAD

**Issue by atsakiridis** [RestComm/Restcomm-Connect#275]
Although client should not send an empty message, it would be nice if Restcomm could check for this edge scenario to avoid exception:

08:36:02,209 ERROR [org.mobicents.servlet.restcomm.sms.SmsService] (RestComm-akka.actor.default-dispatcher-3981) Parse error reading content null with content type text/plain: java.lang.IllegalArgumentException: Parse error reading content null with content type text/plain
	at org.mobicents.servlet.sip.message.SipServletMessageImpl.setContent(SipServletMessageImpl.java:1391)
	at org.mobicents.servlet.sip.message.SipServletRequestImpl.setContent(SipServletRequestImpl.java:2275)
	at org.mobicents.servlet.restcomm.telephony.util.B2BUAHelper.redirectToB2BUA(B2BUAHelper.java:134) [restcomm.telephony.api-7.3.0.1126.jar:]
	at org.mobicents.servlet.restcomm.sms.SmsService.message(SmsService.java:142) [restcomm.sms-7.3.0.1126.jar:]
	at org.mobicents.servlet.restcomm.sms.SmsService.onReceive(SmsService.java:304) [restcomm.sms-7.3.0.1126.jar:]
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:159) [akka-actor_2.10-2.1.2.jar:]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:425) [akka-actor_2.10-2.1.2.jar:]
	at akka.actor.ActorCell.invoke(ActorCell.scala:386) [akka-actor_2.10-2.1.2.jar:]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:230) [akka-actor_2.10-2.1.2.jar:]
	at akka.dispatch.Mailbox.run(Mailbox.scala:212) [akka-actor_2.10-2.1.2.jar:]
	at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:506) [akka-actor_2.10-2.1.2.jar:]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:262) [scala-library-2.10.1.jar:]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:975) [scala-library-2.10.1.jar:]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1478) [scala-library-2.10.1.jar:]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104) [scala-library-2.10.1.jar:]
Caused by: java.lang.NullPointerException: null content
	at gov.nist.javax.sip.message.SIPMessage.setContent(SIPMessage.java:1312) [jain-sip-ri-7.0.3.206.jar:7.0.3.206]
	at org.mobicents.servlet.sip.message.SipServletMessageImpl.setContent(SipServletMessageImpl.java:1386)
	... 14 more

Here's the SIP message for reference:

MESSAGE sip:bob@54.225.212.193:5080 SIP/2.0
Via: SIP/2.0/UDP 192.168.2.49;rport=5062;branch=z9hG4bKZD7rFaty85QtQ;received=79.166.250.82
Max-Forwards: 70
From: <sip:alice@telestax.com>;tag=XBFe2p8NF1e2N
To: <sip:bob@54.225.212.193:5080>
Call-ID: f628044a-7fd8-1233-b0ae-81364e8a00ce
CSeq: 76072211 MESSAGE
User-Agent: sofia-sip/1.12.11
Allow: INVITE,ACK,BYE,CANCEL,OPTIONS,PRACK,MESSAGE,SUBSCRIBE,NOTIFY,REFER,UPDATE
Supported: timer,100rel
Proxy-Authorization: Digest username="alice",realm="54.225.212.193",nonce="38303630373566352d316136312d346",algorithm=MD5,uri="sip:bob@54.225.212.193:5080",response="4c0ff4d7b567cbf788f820f07bb7159c"
Content-Type: text/plain
Content-Length: 0

**Comment by deruelle** [comment]
@croufay please take this one as part of your work on SMS/SMPP And Messages to WebRTC Clients
