### ISSUE TITLE
Using conference-app.zip application with Dialogic JSR 309 Connector and XMS - ERROR mscontrol.DlgcSync2AsyncMonitor - 129 RestComm-akka.actor.default-dispatcher-16 Error Timeout Error Executing What: Process SDP OFFER Request

### ISSUE THREAD

**Issue by RomanDS** [RestComm/Restcomm-Connect#789]
using: Mobicents-Restcomm-JBoss-AS7-7.5.0.24
If you look at the summery bellow, the line 112821 is where the task of sending out an Invite actually being scheduled. Which seems to be entire 8 seconds after the sendSipMessage(). Because of that Dialogic JSR 309 connector 2 second timer kicks in and reports an error. From there things are out of sync.
[server.zip](https://github.com/RestComm/RestComm-Core/files/89641/server.zip)
Q: why is it being held for so long?

sasId: a9c0ea6a;RestComm
DlgcXNetworkConnection@2d9e1207
XNC-2b79a32a71c08
MSS-Executor-Thread-8
MS-2b79a2887f01f
media server=146.152.122.168
Call-ID: baf4b912b6d6b10fc29143c976f08842@146.152.122.146

Timeline:
8010 - 09:21:37,493 INFO  [com.vendor.dialogic.javax.media.mscontrol.sip.DlgcSipB2BUA - 539]
(MSS-Executor-Thread-8) JSR309:sendSipMessage() :
SIP REQUEST TO BE SENT TO XMS :INVITE sip:msml=28971@146.152.122.168:5060 SIP/2.0

57007 -  09:21:42,391 ERROR mscontrol.DlgcSync2AsyncMonitor - 129 RestComm-akka.actor.default-dispatcher-16
Error Timeout Error Executing What: Process SDP OFFER Request

112821 - 09:21:45,338 DEBUG MSS-Executor-Thread-13 sip.DlgcSipB2BUA - 432 DlgcSipServlet:scheduleTask()

**Comment by jaimecasero** [comment]
Hi @RomanDS 

Let me have a look to that log file.

**Comment by jaimecasero** [comment]
hrosa [11:29 AM] 
@jaime.casero: a hint here, this issue surfaces during load tests where call rate is 100CPS

**Comment by jaimecasero** [comment]
Hi @RomanDS ,

I can only explain so much delay if there are many schedulings being requested.

I guess you are invoking the SIPServlet Timer service here. This service uses a ScheduledThreadPoolExecutor with 4 threads for each application. It may be your app needs more threads (if timer threads are used to send invite it may be affected by NWT).

Looking at the log file i can see "DlgcSipServlet:scheduleTask()" 1325 occurrences, in a 16 seconds interval. It is not much scheduling, but is not low either. 1325/16 = 82timers/sec -> 82 / 4 threads = 20 timers/secThread -> 1000 ms / 20 = 50 -> 50 ms for each task. Again it should be enough, but it depends on what it is scheduled.

To confirm this hypothesis I would suggests to review the state for threads with name 
<applicationName> + "_sip_default_sas_timer_service" + <N> .

To do that you could invoke jstack -f <pid> | grep "_sip_default_sas_timer_service" form time to time.

I will discuss with Henrique if i can attach a profiler to his instance so i can monitor thread activity in real time.

In the meantime im preparing a simple patch with 64 threads for your app (it should be more than enough). If we confirm that, a new env setting will be created for you to tune your app.

Regards

**Comment by jaimecasero** [comment]
[sip-servlets-impl-3.0.0-SNAPSHOT.jar.zip](https://github.com/RestComm/RestComm-Core/files/90304/sip-servlets-impl-3.0.0-SNAPSHOT.jar.zip)

@RomanDS  please try this jar on your installation. It has more threads available for the timer service (64)

**Comment by RomanDS** [comment]
Hi,
The existing file is: sip-servlets-impl-3.1.649.jar. is that an issue that the overlay is 3.0 and existing is 3.1?

**Comment by jaimecasero** [comment]
Hi Roman,
Yes it could be a problem, let me check your build dependencies. Sorry i
miss to check first.

Regards

**Comment by jaimecasero** [comment]
@RomanDS  I check your build, it is based on sip-servlets-catalina-7-3.1.631 . So in this case, nevermind about version, the patch should work for you . Keep a copy of the orginal jar file so you can recover.

**Comment by RomanDS** [comment]
Hi @jaimecasero, well, does not seem to work. I get an exception:

12:46:29,105 INFO  [org.jboss.modules - 750] (main) JBoss Modules version 1.2.0.CR1
12:46:29,397 INFO  [org.jboss.msc - 104] (main) JBoss MSC version 1.0.4.GA
12:46:29,556 INFO  [org.jboss.as - 93] (MSC service thread 1-8) JBAS015899: JBoss AS 7.2.0.Final "Janus" starting
12:46:30,259 ERROR [org.jboss.as.server - 316] (Controller Boot Thread) JBAS015956: Caught exception during boot: org.jboss.as.controller.persistence.ConfigurationPersistenceException: JBAS014676: Failed to parse configuration
       at org.jboss.as.controller.persistence.XmlConfigurationPersister.load(XmlConfigurationPersister.java:141) [jboss-as-controller-7.2.0.Final.jar:7.2.0.Final]
       at org.jboss.as.server.ServerService.boot(ServerService.java:308) [jboss-as-server-7.2.0.Final.jar:7.2.0.Final]
       at org.jboss.as.controller.AbstractControllerService$1.run(AbstractControllerService.java:188) [jboss-as-controller-7.2.0.Final.jar:7.2.0.Final]
       at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_80]
Caused by: javax.xml.stream.XMLStreamException: JBAS014674: Failed to load module org.jboss.as.ee
       at org.jboss.as.controller.parsing.ExtensionXml.parseExtensions(ExtensionXml.java:154) [jboss-as-controller-7.2.0.Final.jar:7.2.0.Final]
       at org.jboss.as.server.parsing.StandaloneXml.readServerElement_1_4(StandaloneXml.java:424) [jboss-as-server-7.2.0.Final.jar:7.2.0.Final]
       at org.jboss.as.server.parsing.StandaloneXml.readElement(StandaloneXml.java:136) [jboss-as-server-7.2.0.Final.jar:7.2.0.Final]
       at org.jboss.as.server.parsing.StandaloneXml.readElement(StandaloneXml.java:103) [jboss-as-server-7.2.0.Final.jar:7.2.0.Final]
       at org.jboss.staxmapper.XMLMapperImpl.processNested(XMLMapperImpl.java:110) [staxmapper-1.1.0.Final.jar:1.1.0.Final]
       at org.jboss.staxmapper.XMLMapperImpl.parseDocument(XMLMapperImpl.java:69) [staxmapper-1.1.0.Final.jar:1.1.0.Final]
       at org.jboss.as.controller.persistence.XmlConfigurationPersister.load(XmlConfigurationPersister.java:133) [jboss-as-controller-7.2.0.Final.jar:7.2.0.Final]
       ... 3 more
Caused by: java.util.concurrent.ExecutionException: javax.xml.stream.XMLStreamException: JBAS014674: Failed to load module
       at java.util.concurrent.FutureTask.report(FutureTask.java:122) [rt.jar:1.7.0_80]
       at java.util.concurrent.FutureTask.get(FutureTask.java:188) [rt.jar:1.7.0_80]
       at org.jboss.as.controller.parsing.ExtensionXml.parseExtensions(ExtensionXml.java:146) [jboss-as-controller-7.2.0.Final.jar:7.2.0.Final]
       ... 9 more
Caused by: javax.xml.stream.XMLStreamException: JBAS014674: Failed to load module
       at org.jboss.as.controller.parsing.ExtensionXml.loadModule(ExtensionXml.java:195) [jboss-as-controller-7.2.0.Final.jar:7.2.0.Final]
       at org.jboss.as.controller.parsing.ExtensionXml.access$000(ExtensionXml.java:68) [jboss-as-controller-7.2.0.Final.jar:7.2.0.Final]
       at org.jboss.as.controller.parsing.ExtensionXml$1.call(ExtensionXml.java:126) [jboss-as-controller-7.2.0.Final.jar:7.2.0.Final]
       at org.jboss.as.controller.parsing.ExtensionXml$1.call(ExtensionXml.java:123) [jboss-as-controller-7.2.0.Final.jar:7.2.0.Final]
       at java.util.concurrent.FutureTask.run(FutureTask.java:262) [rt.jar:1.7.0_80]
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [rt.jar:1.7.0_80]
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [rt.jar:1.7.0_80]
       at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_80]
       at org.jboss.threads.JBossThread.run(JBossThread.java:122) [jboss-threads-2.1.0.Final.jar:2.1.0.Final]
Caused by: org.jboss.modules.ModuleLoadException: Error loading module from /opt/Mobicents-Restcomm-JBoss-AS7-7.5.0.24/modules/system/layers/base/org/mobicents/libs/main/module.xml
       at org.jboss.modules.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:280) [jboss-modules.jar:1.2.0.CR1]
       at org.jboss.modules.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:244) [jboss-modules.jar:1.2.0.CR1]
       at org.jboss.modules.LocalModuleFinder.findModule(LocalModuleFinder.java:115) [jboss-modules.jar:1.2.0.CR1]
       at org.jboss.modules.ModuleLoader.findModule(ModuleLoader.java:389) [jboss-modules.jar:1.2.0.CR1]
       at org.jboss.modules.ModuleLoader.loadModuleLocal(ModuleLoader.java:293) [jboss-modules.jar:1.2.0.CR1]
       at org.jboss.modules.ModuleLoader.preloadModule(ModuleLoader.java:240) [jboss-modules.jar:1.2.0.CR1]
       at org.jboss.modules.Module.addPaths(Module.java:840) [jboss-modules.jar:1.2.0.CR1]
       at org.jboss.modules.Module.link(Module.java:1194) [jboss-modules.jar:1.2.0.CR1]
       at org.jboss.modules.Module.relinkIfNecessary(Module.java:1222) [jboss-modules.jar:1.2.0.CR1]
       at org.jboss.modules.ModuleLoader.loadModule(ModuleLoader.java:226) [jboss-modules.jar:1.2.0.CR1]
       at org.jboss.as.controller.parsing.ExtensionXml.loadModule(ExtensionXml.java:177) [jboss-as-controller-7.2.0.Final.jar:7.2.0.Final]
       ... 8 more
Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[29,62]
Message: Failed to add resource root 'sip-servlets-impl-3.1.649.jar' at path 'sip-servlets-impl-3.1.649.jar'
       at org.jboss.modules.ModuleXmlParser.parseResourceRoot(ModuleXmlParser.java:743) [jboss-modules.jar:1.2.0.CR1]
       at org.jboss.modules.ModuleXmlParser.parseResources(ModuleXmlParser.java:699) [jboss-modules.jar:1.2.0.CR1]
       at org.jboss.modules.ModuleXmlParser.parseModuleContents(ModuleXmlParser.java:526) [jboss-modules.jar:1.2.0.CR1]
       at org.jboss.modules.ModuleXmlParser.parseDocument(ModuleXmlParser.java:357) [jboss-modules.jar:1.2.0.CR1]
       at org.jboss.modules.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:275) [jboss-modules.jar:1.2.0.CR1]
       ... 18 more

12:46:30,311 FATAL [org.jboss.as.server - 325] (Controller Boot Thread) JBAS015957: Server boot has failed in an unrecoverable manner; exiting. See previous messages for details.
12:46:30,347 INFO  [org.jboss.as - 183] (MSC service thread 1-4) JBAS015950: JBoss AS 7.2.0.Final "Janus" stopped in 3ms

**Comment by jaimecasero** [comment]
@RomanDS 
Did you rename my file with the existing library?

It seems server fail to load jar file "sip-servlets-impl-3.1.649.jar".

Steps should be:
1.rename originalfile to <originalfile>.bck
2.Move patch lib to the same dir.
3.Rename patchlib to original lib name
4.restart server.

I guess you did it right, but i wanted to clarify....

**Comment by RomanDS** [comment]
Hm.. that is what I did.. but maybe I also need to get rid of the index file:

[cid:image001.png@01D14EDB.84E21B30]

**Comment by jaimecasero** [comment]
i dont think is necessary. Let me try with your build Mobicents-Restcomm-JBoss-AS7-7.5.0.24

**Comment by jaimecasero** [comment]
@RomanDS  reproduced, let me check what is the issue, i will create another patch soon

**Comment by RomanDS** [comment]
Phew! Good ☺

**Comment by jaimecasero** [comment]
[sip-servlets-impl-3.1.649-64Threads.jar.zip](https://github.com/RestComm/RestComm-Core/files/90945/sip-servlets-impl-3.1.649-64Threads.jar.zip)

find attached new patch. That works in my env with your build

**Comment by RomanDS** [comment]
Hello @jaimecasero,
Well, I am afraid that this is still not working for me. The new one seems smaller in size so not sure if that has any bearing on the issue.

[cid:image001.png@01D14F8A.D07191C0]


Best regards,
Roman

**Comment by jaimecasero** [comment]
Hi @RomanDS 
Your sipServletImpl jar file should be 448150 bytes.

The one I sent you should be 450.175 bytes. So its a little but greater than the original one....

I happened to zip the jar file for sec reason (431.299). Did you unzip that?

**Comment by RomanDS** [comment]
Ooops, yes, my bad. I also realized that it needs to be exact name as the original one. I am going to run the test now. Thanks!

**Comment by jaimecasero** [comment]
@RomanDS  no problem, it was my fault to not warn you in advance. Sorry, and good luck, please keep update with your progress

**Comment by RomanDS** [comment]
Hello @jaimecasero,
Well, no worries, I think you did mentioned some of it before…

Anyway, I tested the overlay and it has seemed to show no Error Executing What: Process SDP OFFER Request errors in two runs of 100cps for 1000 calls total at 100 max.

Let me know when new build is out with this change so I have no chance of “forgetting” putting this overlay in ☺

Thanks a lot for your help!

Best regards,
Roman

**Comment by jaimecasero** [comment]
@RomanDS  that is good news. Now i need to make this hardcoded value configurable from properties or sip descriptor. I will let you know when is ready.

**Comment by deruelle** [comment]
Good investigation work @jaimecasero ! Great team work guys ! Keep it up ;)

**Comment by deruelle** [comment]
@jaimecasero can you help guide @xhoaluu on how to make that configurable ?

**Comment by xhoaluu** [comment]
I'm ready. Let I go through it a bit first.

**Comment by jaimecasero** [comment]
@xhoaluu  as disucussed, I think it make sense to use a context param in this case. It will allow each application to configure the number of its dedicated TimerService. In addition, the TimerService is created from the SipStandardContext, so passing the parameter from the context descriptor to the TimerService constructor will be obvious..

**Comment by xhoaluu** [comment]
Closed https://github.com/RestComm/sip-servlets/pull/188
