### ISSUE TITLE
Dialogic JSR309 driver throws ClassCastException for outbound calls

### ISSUE THREAD

**Issue by hrosa** [RestComm/Restcomm-Connect#803]
While testing Dial SIP scenarios with Dialogic XMS, the JSR309 driver frequently throws the following exception:

```
05:19:17,401 ERROR [org.mobicents.servlet.sip.core.dispatchers.DispatchTask] (Mobicents-SIP-Servlets-UDPMessageChannelThread-57) Unexpected exception while processing message SIP/2.0 200 OK
From: "dlgjmc" <sip:dlgjmc@10.169.104.27:5080>;tag=70106168_21fc08c1_57a5b08a_5396f2ef
To: "MediaServer" <sip:msml=71889@52.71.28.217:5060>;tag=d84424d0-500000a-13c4-65014-778a-1741b4ab-778a
Call-ID: 88627ef16407f7bb880ef422b8aff8b0@10.169.104.27
CSeq: 3 INFO
Via: SIP/2.0/UDP 54.204.246.212:5080;branch=z9hG4bK5396f2ef_57a5b08a_a08272cb-b05c-4354-b5f0-692cc91332d1
Contact: <sip:msml=71889@52.71.28.217:5060>
Allow: INVITE,CANCEL,ACK,BYE,OPTIONS,INFO,REFER,NOTIFY,UPDATE
Content-Type: application/xml
Content-Length: 96

<?xml version="1.0" encoding="UTF-8"?>
<msml version="1.1">
	<result response="200"/>
</msml>: org.mobicents.servlet.sip.core.DispatcherException: Unexpected exception while processing response : SIP/2.0 200 OK
From: "dlgjmc" <sip:dlgjmc@10.169.104.27:5080>;tag=70106168_21fc08c1_57a5b08a_5396f2ef
To: "MediaServer" <sip:msml=71889@52.71.28.217:5060>;tag=d84424d0-500000a-13c4-65014-778a-1741b4ab-778a
Call-ID: 88627ef16407f7bb880ef422b8aff8b0@10.169.104.27
CSeq: 3 INFO
Via: SIP/2.0/UDP 54.204.246.212:5080;branch=z9hG4bK5396f2ef_57a5b08a_a08272cb-b05c-4354-b5f0-692cc91332d1
Contact: <sip:msml=71889@52.71.28.217:5060>
Allow: INVITE,CANCEL,ACK,BYE,OPTIONS,INFO,REFER,NOTIFY,UPDATE
Content-Type: application/xml
Content-Length: 96

<?xml version="1.0" encoding="UTF-8"?>
<msml version="1.1">
	<result response="200"/>
</msml>
	at org.mobicents.servlet.sip.core.dispatchers.ResponseDispatcher$1.dispatch(ResponseDispatcher.java:503) [sip-servlets-impl-3.1.649.jar:3.1.649]
	at org.mobicents.servlet.sip.core.dispatchers.DispatchTask.dispatchAndHandleExceptions(DispatchTask.java:58) [sip-servlets-impl-3.1.649.jar:3.1.649]
	at org.mobicents.servlet.sip.core.dispatchers.ResponseDispatcher.dispatchMessage(ResponseDispatcher.java:524) [sip-servlets-impl-3.1.649.jar:3.1.649]
	at org.mobicents.servlet.sip.core.SipApplicationDispatcherImpl.processResponse(SipApplicationDispatcherImpl.java:1118) [sip-servlets-impl-3.1.649.jar:3.1.649]
	at gov.nist.javax.sip.EventScanner.deliverResponseEvent(EventScanner.java:317) [jain-sip-ri-1.2.259.jar:1.2.259]
	at gov.nist.javax.sip.EventScanner.deliverEvent(EventScanner.java:148) [jain-sip-ri-1.2.259.jar:1.2.259]
	at gov.nist.javax.sip.SipProviderImpl.handleEvent(SipProviderImpl.java:185) [jain-sip-ri-1.2.259.jar:1.2.259]
	at gov.nist.javax.sip.DialogFilter.processResponse(DialogFilter.java:1514) [jain-sip-ri-1.2.259.jar:1.2.259]
	at gov.nist.javax.sip.stack.SIPClientTransactionImpl.nonInviteClientTransaction(SIPClientTransactionImpl.java:630) [jain-sip-ri-1.2.259.jar:1.2.259]
	at gov.nist.javax.sip.stack.SIPClientTransactionImpl.processResponse(SIPClientTransactionImpl.java:535) [jain-sip-ri-1.2.259.jar:1.2.259]
	at gov.nist.javax.sip.stack.SIPClientTransactionImpl.processResponse(SIPClientTransactionImpl.java:1622) [jain-sip-ri-1.2.259.jar:1.2.259]
	at gov.nist.javax.sip.stack.UDPMessageChannel.processMessage(UDPMessageChannel.java:611) [jain-sip-ri-1.2.259.jar:1.2.259]
	at gov.nist.javax.sip.stack.UDPMessageChannel.processIncomingDataPacket(UDPMessageChannel.java:514) [jain-sip-ri-1.2.259.jar:1.2.259]
	at gov.nist.javax.sip.stack.UDPMessageChannel.run(UDPMessageChannel.java:319) [jain-sip-ri-1.2.259.jar:1.2.259]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_91]
Caused by: java.lang.ClassCastException: com.vendor.dialogic.javax.media.mscontrol.networkconnection.DlgcCreatedState cannot be cast to com.vendor.dialogic.javax.media.mscontrol.networkconnection.DlgcXSdpPortManagerStates
	at com.vendor.dialogic.javax.media.mscontrol.networkconnection.DlgcXSdpPortManagerFSM.evSipInfo(DlgcXSdpPortManagerFSM.java:187)
	at com.vendor.dialogic.javax.media.mscontrol.networkconnection.DlgcXNetworkConnection.processSipInfo(DlgcXNetworkConnection.java:190)
	at com.vendor.dialogic.javax.media.mscontrol.sip.DlgcXmsB2BUAReceiver.processSipResponseInfo(DlgcXmsB2BUAReceiver.java:396)
	at com.vendor.dialogic.javax.media.mscontrol.sip.DlgcAbstractB2BUAReceiver.processSipResponseDoAction(DlgcAbstractB2BUAReceiver.java:193)
	at com.vendor.dialogic.javax.media.mscontrol.sip.DlgcSipB2BUA.processSipResponseDoAction(DlgcSipB2BUA.java:698)
	at com.vendor.dialogic.javax.media.mscontrol.sip.DlgcSipB2BUA$DlgcReceiveResponseTask.run(DlgcSipB2BUA.java:671)
	at com.vendor.dialogic.javax.media.mscontrol.sip.DlgcSipB2BUA.processSipResponse(DlgcSipB2BUA.java:649)
	at com.vendor.dialogic.javax.media.mscontrol.sip.DlgcSipServlet.doResponse(DlgcSipServlet.java:155)
	at javax.servlet.sip.SipServlet.service(SipServlet.java:334) [sip-servlets-spec-3.1.649.jar:3.1.649]
	at org.mobicents.servlet.sip.core.dispatchers.MessageDispatcher.callServlet(MessageDispatcher.java:459) [sip-servlets-impl-3.1.649.jar:3.1.649]
	at org.mobicents.servlet.sip.core.dispatchers.ResponseDispatcher$1.dispatch(ResponseDispatcher.java:491) [sip-servlets-impl-3.1.649.jar:3.1.649]
	... 14 more
```

**Comment by RomanDS** [comment]
Hi @hrosa, do you have a full log for this scenario.

**Comment by RomanDS** [comment]
Hi @hrosa, I just realized that you indicated that this error does no longer occur with the latest run you have done. Lets keep an eye for this and Ill need full set of logs for this to traverse.
