### ISSUE TITLE
Support for multiple Media servers and routing rules for routing MGCP traffic and patching SDP

### ISSUE THREAD

**Issue by gvagenas** [RestComm/Restcomm-Connect#932]

**Comment by deruelle** [comment]
First task here should be that Restcomm is capable of talking to multiple Media Servers instances. We can imagine at first doing a round robin algorithm for selecting the Media Server automatically. 

The second step would be to make the Media Server algorithm selection pluggable so that custom algorithm could be used to better assign specific calls to specific media server instances.

**Comment by atika2k** [comment]
Hi @deruelle @gvagenas 

I considered this scenario:
I have 3 working MS instances  and one Restcomm instance which communicates with them. Each of this MS instances has certain CPU load, based on processes of other Restcomm instance connections. Here, i suppose i should consider the response time,resource use and network congestion as well. So, based on these parameters, Restcomm should be able to select the most appropriate MS which will make the quickest respond. 

Does this scenario covers the needs for the first part?
Do we need to handle also the load balancing/distribution?

**Comment by deruelle** [comment]
@atika2k As a first step, let's keep it simple and use a round robin algorithm to select the Media Server and potentially allow a system to create pluggable algorithms with default algorithm being round robin.

**Comment by deruelle** [comment]
@atika2k were you able to make progress on this or there is blockers ?

**Comment by atika2k** [comment]
@deruelle i've been away due to other obligations. I will update as soon as possible.

**Comment by deruelle** [comment]
@atika2k no worries, actually we have an important deadline to meet on this one, so I'm assigning this to a member of the team as well to take over. Feel free to share your work or sync up with @maria-farooq on that.

**Comment by maria-farooq** [comment]
Hi @gvagenas , i have some change in `Bootstrapper.java` in `restcomm.application` project, when i build the project i get a war file `restcomm.application-7.8.0-SNAPSHOT.war` any help how can i deploy it in some short way?
or should i just replace it with `$RESTCOMM_HOME/standalone/deployments/restcomm.war`

Thanks 
Maria

**Comment by maria-farooq** [comment]
Latest status on ticket is:
CallControler and BootStrap is changed in order to handle multiple media servers
My local setup is some thing like following
`Restcomm is running on 192.168.8.102`
`Media-Server1 is running on 192.168.8.102:2427`
`Media-Server2 is running on 127.0.0.1:2428`
`Restcomm to MS1 mgcp stack binding fails due following exception`
`Restcomm to MS2 mgcp stack binding is successful`


```
02:37:00,485 INFO  [org.mobicents.servlet.restcomm.Bootstrapper] (ServerService Thread Pool -- 50) $$$$$$$$$$$$$$$$$$$$$$$$$$$$$ New Edition $$$$$$$$$$$$$$$$$$$$$$$$$$$$$
02:37:00,485 INFO  [org.mobicents.servlet.restcomm.Bootstrapper] (ServerService Thread Pool -- 50) Available Media gateways are: 2
02:37:00,490 INFO  [com.telestax.servlet.MonitoringService] (RestComm-akka.actor.default-dispatcher-4) Monitoring Service started
02:37:00,491 INFO  [org.mobicents.servlet.restcomm.Bootstrapper] (ServerService Thread Pool -- 50) mgcp-servers.mgcp-server(0).local-address: 192.168.8.2
02:37:00,491 INFO  [org.mobicents.servlet.restcomm.Bootstrapper] (ServerService Thread Pool -- 50) mgcp-servers.mgcp-server(0).local-port: 2727
02:37:00,492 INFO  [org.mobicents.servlet.restcomm.Bootstrapper] (ServerService Thread Pool -- 50) mgcp-servers.mgcp-server(0).remote-address: 192.168.8.2
02:37:00,492 INFO  [org.mobicents.servlet.restcomm.Bootstrapper] (ServerService Thread Pool -- 50) mgcp-servers.mgcp-server(0).remote-port: 2427
02:37:00,492 INFO  [org.mobicents.servlet.restcomm.Bootstrapper] (ServerService Thread Pool -- 50) mgcp-servers.mgcp-server(0).external-address: null
02:37:00,493 INFO  [org.mobicents.servlet.restcomm.Bootstrapper] (ServerService Thread Pool -- 50) mgcp-servers.mgcp-server(1).local-address: 127.0.0.1
02:37:00,493 INFO  [org.mobicents.servlet.restcomm.Bootstrapper] (ServerService Thread Pool -- 50) mgcp-servers.mgcp-server(1).local-port: 2728
02:37:00,494 INFO  [org.mobicents.servlet.restcomm.Bootstrapper] (ServerService Thread Pool -- 50) mgcp-servers.mgcp-server(1).remote-address: 127.0.0.1
02:37:00,494 INFO  [org.mobicents.servlet.restcomm.Bootstrapper] (ServerService Thread Pool -- 50) mgcp-servers.mgcp-server(1).remote-port: 2428
02:37:00,494 INFO  [org.mobicents.servlet.restcomm.Bootstrapper] (ServerService Thread Pool -- 50) mgcp-servers.mgcp-server(1).external-address: null
02:37:00,501 WARN  [org.mobicents.protocols.mgcp.stack.JainMgcpStackImpl] (RestComm-akka.actor.default-dispatcher-2) Failed to locate properties file, using default values
02:37:00,504 ERROR [org.mobicents.protocols.mgcp.stack.JainMgcpStackImpl] (RestComm-akka.actor.default-dispatcher-2) java.net.BindException: Can't assign requested address
02:37:00,507 ERROR [org.mobicents.servlet.restcomm.mgcp.MediaGateway] (RestComm-akka.actor.default-dispatcher-4) Failed to find a local port 2727 to bound stack: java.lang.RuntimeException: Failed to find a local port 2727 to bound stack
	at org.mobicents.protocols.mgcp.stack.JainMgcpStackImpl.init(JainMgcpStackImpl.java:171) [mgcp-driver-3.0.2.FINAL.jar:3.0.2.FINAL]
	at org.mobicents.protocols.mgcp.stack.JainMgcpStackImpl.createProvider(JainMgcpStackImpl.java:249) [mgcp-driver-3.0.2.FINAL.jar:3.0.2.FINAL]
	at org.mobicents.servlet.restcomm.mgcp.MediaGateway.powerOn(MediaGateway.java:221) [restcomm.mgcp-7.8.0-SNAPSHOT.jar:]
	at org.mobicents.servlet.restcomm.mgcp.MediaGateway.onReceive(MediaGateway.java:267) [restcomm.mgcp-7.8.0-SNAPSHOT.jar:]
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:159) [akka-actor_2.10-2.1.2.jar:]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:425) [akka-actor_2.10-2.1.2.jar:]
	at akka.actor.ActorCell.invoke(ActorCell.scala:386) [akka-actor_2.10-2.1.2.jar:]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:230) [akka-actor_2.10-2.1.2.jar:]
	at akka.dispatch.Mailbox.run(Mailbox.scala:212) [akka-actor_2.10-2.1.2.jar:]
	at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:506) [akka-actor_2.10-2.1.2.jar:]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:262) [scala-library-2.10.1.jar:]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:975) [scala-library-2.10.1.jar:]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1478) [scala-library-2.10.1.jar:]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104) [scala-library-2.10.1.jar:]

02:37:00,535 WARN  [org.mobicents.protocols.mgcp.stack.JainMgcpStackImpl] (RestComm-akka.actor.default-dispatcher-2) Failed to locate properties file, using default values
02:37:00,536 INFO  [org.mobicents.protocols.mgcp.stack.JainMgcpStackImpl] (RestComm-akka.actor.default-dispatcher-2) Jain Mgcp stack bound to IP /127.0.0.1 and UDP port 2728
02:37:00,537 INFO  [stdout] (RestComm-akka.actor.default-dispatcher-2) Jain Mgcp stack bound to IP /127.0.0.1 and UDP port 2728
```

**Comment by maria-farooq** [comment]
i am using MAC OSx 10.9.5 and i am not getting correct port (used/free) information, i will try a few things (like with different ports)and then in case i remained stuck i will raise.
thanks

**Comment by gvagenas** [comment]
@maria-farooq after you start RMS servers and before you start Restcomm check if ports 2727 and 2728 are already binded by another process. 
At Linux you can do it with "netstat -anp | grep 2727". For OSx check the answer here : http://stackoverflow.com/questions/4421633/who-is-listening-on-a-given-tcp-port-on-mac-os-x#4421674

There is a chance that a previous Restcomm process that didn't stopped properly keeps port 2727.

George

**Comment by maria-farooq** [comment]
thanks @gvagenas,
Strange thing is that port is not used by any process 

here is port list when only both RMS are running:
```
java      6390    mariafarooq  101u  IPv6 0x2b91ac7a3b997361      0t0    UDP 127.0.0.1:2428
java      6403    mariafarooq  101u  IPv6 0x2b91ac7a3aae22f9      0t0    UDP 192.168.8.102:2427
```

Here is update list after starting restcomm `screen -dmS 'restcomm' bin/standalone.sh -b 192.168.8.102`

```
java      6390    mariafarooq  101u  IPv6 0x2b91ac7a3b997361      0t0    UDP 127.0.0.1:2428
java      6403    mariafarooq  101u  IPv6 0x2b91ac7a3aae22f9      0t0    UDP 192.168.8.102:2427
java      6794    mariafarooq  389u  IPv4 0x2b91ac7a3bd80f91      0t0    UDP 192.168.8.102:5080
java      6794    mariafarooq  458u  IPv4 0x2b91ac7a3bd94c81      0t0    UDP 127.0.0.1:2728
java      6794    mariafarooq  475u  IPv4 0x2b91ac7a3bd80609      0t0    UDP *:*
```

But i am still getting same exception:
```
17:00:26,701 INFO  [org.mobicents.servlet.restcomm.Bootstrapper] (ServerService Thread Pool -- 55) $$$$$$$$$$$$$$$$$$$$$$$$$$$$$ New Edition $$$$$$$$$$$$$$$$$$$$$$$$$$$$$
17:00:26,702 INFO  [org.mobicents.servlet.restcomm.Bootstrapper] (ServerService Thread Pool -- 55) Available Media gateways are: 2
17:00:26,702 INFO  [com.telestax.servlet.MonitoringService] (RestComm-akka.actor.default-dispatcher-3) Monitoring Service started
17:00:26,705 INFO  [org.mobicents.servlet.restcomm.Bootstrapper] (ServerService Thread Pool -- 55) mgcp-servers.mgcp-server(0).local-address: 127.0.0.1
17:00:26,705 INFO  [org.mobicents.servlet.restcomm.Bootstrapper] (ServerService Thread Pool -- 55) mgcp-servers.mgcp-server(0).local-port: 2728
17:00:26,706 INFO  [org.mobicents.servlet.restcomm.Bootstrapper] (ServerService Thread Pool -- 55) mgcp-servers.mgcp-server(0).remote-address: 127.0.0.1
17:00:26,706 INFO  [org.mobicents.servlet.restcomm.Bootstrapper] (ServerService Thread Pool -- 55) mgcp-servers.mgcp-server(0).remote-port: 2427
17:00:26,706 INFO  [org.mobicents.servlet.restcomm.Bootstrapper] (ServerService Thread Pool -- 55) mgcp-servers.mgcp-server(0).external-address: null
17:00:26,707 INFO  [org.mobicents.servlet.restcomm.Bootstrapper] (ServerService Thread Pool -- 55) mgcp-servers.mgcp-server(1).local-address: 192.168.8.2
17:00:26,708 INFO  [org.mobicents.servlet.restcomm.Bootstrapper] (ServerService Thread Pool -- 55) mgcp-servers.mgcp-server(1).local-port: 2727
17:00:26,709 INFO  [org.mobicents.servlet.restcomm.Bootstrapper] (ServerService Thread Pool -- 55) mgcp-servers.mgcp-server(1).remote-address: 192.168.8.2
17:00:26,709 INFO  [org.mobicents.servlet.restcomm.Bootstrapper] (ServerService Thread Pool -- 55) mgcp-servers.mgcp-server(1).remote-port: 2427
17:00:26,710 INFO  [org.mobicents.servlet.restcomm.Bootstrapper] (ServerService Thread Pool -- 55) mgcp-servers.mgcp-server(1).external-address: null
17:00:26,714 WARN  [org.mobicents.protocols.mgcp.stack.JainMgcpStackImpl] (RestComm-akka.actor.default-dispatcher-5) Failed to locate properties file, using default values
17:00:26,716 INFO  [org.mobicents.protocols.mgcp.stack.JainMgcpStackImpl] (RestComm-akka.actor.default-dispatcher-5) Jain Mgcp stack bound to IP /127.0.0.1 and UDP port 2728
17:00:26,718 INFO  [stdout] (RestComm-akka.actor.default-dispatcher-5) Jain Mgcp stack bound to IP /127.0.0.1 and UDP port 2728
17:00:26,731 WARN  [org.mobicents.protocols.mgcp.stack.JainMgcpStackImpl] (RestComm-akka.actor.default-dispatcher-5) Failed to locate properties file, using default values
17:00:26,732 ERROR [org.mobicents.protocols.mgcp.stack.JainMgcpStackImpl] (RestComm-akka.actor.default-dispatcher-5) java.net.BindException: Can't assign requested address
17:00:26,734 ERROR [org.mobicents.servlet.restcomm.mgcp.MediaGateway] (RestComm-akka.actor.default-dispatcher-3) Failed to find a local port 2727 to bound stack: java.lang.RuntimeException: Failed to find a local port 2727 to bound stack
	at org.mobicents.protocols.mgcp.stack.JainMgcpStackImpl.init(JainMgcpStackImpl.java:171) [mgcp-driver-3.0.2.FINAL.jar:3.0.2.FINAL]
	at org.mobicents.protocols.mgcp.stack.JainMgcpStackImpl.createProvider(JainMgcpStackImpl.java:249) [mgcp-driver-3.0.2.FINAL.jar:3.0.2.FINAL]
	at org.mobicents.servlet.restcomm.mgcp.MediaGateway.powerOn(MediaGateway.java:221) [restcomm.mgcp-7.8.0-SNAPSHOT.jar:]
	at org.mobicents.servlet.restcomm.mgcp.MediaGateway.onReceive(MediaGateway.java:267) [restcomm.mgcp-7.8.0-SNAPSHOT.jar:]
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:159) [akka-actor_2.10-2.1.2.jar:]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:425) [akka-actor_2.10-2.1.2.jar:]
	at akka.actor.ActorCell.invoke(ActorCell.scala:386) [akka-actor_2.10-2.1.2.jar:]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:230) [akka-actor_2.10-2.1.2.jar:]
	at akka.dispatch.Mailbox.run(Mailbox.scala:212) [akka-actor_2.10-2.1.2.jar:]
	at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:506) [akka-actor_2.10-2.1.2.jar:]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:262) [scala-library-2.10.1.jar:]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:975) [scala-library-2.10.1.jar:]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1478) [scala-library-2.10.1.jar:]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104) [scala-library-2.10.1.jar:]
```

Hi @hrosa I tried different than default port as well, i tried with 2729 instead of 2727 and still got same exception

```
17:12:17,393 INFO  [org.mobicents.servlet.restcomm.Bootstrapper] (ServerService Thread Pool -- 53) $$$$$$$$$$$$$$$$$$$$$$$$$$$$$ New Edition $$$$$$$$$$$$$$$$$$$$$$$$$$$$$
17:12:17,394 INFO  [com.telestax.servlet.MonitoringService] (RestComm-akka.actor.default-dispatcher-4) Monitoring Service started
17:12:17,394 INFO  [org.mobicents.servlet.restcomm.Bootstrapper] (ServerService Thread Pool -- 53) Available Media gateways are: 2
17:12:17,399 INFO  [org.mobicents.servlet.restcomm.Bootstrapper] (ServerService Thread Pool -- 53) mgcp-servers.mgcp-server(0).local-address: 127.0.0.1
17:12:17,400 INFO  [org.mobicents.servlet.restcomm.Bootstrapper] (ServerService Thread Pool -- 53) mgcp-servers.mgcp-server(0).local-port: 2728
17:12:17,401 INFO  [org.mobicents.servlet.restcomm.Bootstrapper] (ServerService Thread Pool -- 53) mgcp-servers.mgcp-server(0).remote-address: 127.0.0.1
17:12:17,401 INFO  [org.mobicents.servlet.restcomm.Bootstrapper] (ServerService Thread Pool -- 53) mgcp-servers.mgcp-server(0).remote-port: 2427
17:12:17,401 INFO  [org.mobicents.servlet.restcomm.Bootstrapper] (ServerService Thread Pool -- 53) mgcp-servers.mgcp-server(0).external-address: null
17:12:17,402 INFO  [org.mobicents.servlet.restcomm.Bootstrapper] (ServerService Thread Pool -- 53) mgcp-servers.mgcp-server(1).local-address: 192.168.8.2
17:12:17,402 INFO  [org.mobicents.servlet.restcomm.Bootstrapper] (ServerService Thread Pool -- 53) mgcp-servers.mgcp-server(1).local-port: 2729
17:12:17,403 INFO  [org.mobicents.servlet.restcomm.Bootstrapper] (ServerService Thread Pool -- 53) mgcp-servers.mgcp-server(1).remote-address: 192.168.8.2
17:12:17,403 INFO  [org.mobicents.servlet.restcomm.Bootstrapper] (ServerService Thread Pool -- 53) mgcp-servers.mgcp-server(1).remote-port: 2427
17:12:17,404 INFO  [org.mobicents.servlet.restcomm.Bootstrapper] (ServerService Thread Pool -- 53) mgcp-servers.mgcp-server(1).external-address: null
17:12:17,409 WARN  [org.mobicents.protocols.mgcp.stack.JainMgcpStackImpl] (RestComm-akka.actor.default-dispatcher-4) Failed to locate properties file, using default values
17:12:17,412 INFO  [org.mobicents.protocols.mgcp.stack.JainMgcpStackImpl] (RestComm-akka.actor.default-dispatcher-4) Jain Mgcp stack bound to IP /127.0.0.1 and UDP port 2728
17:12:17,413 INFO  [stdout] (RestComm-akka.actor.default-dispatcher-4) Jain Mgcp stack bound to IP /127.0.0.1 and UDP port 2728
17:12:17,429 WARN  [org.mobicents.protocols.mgcp.stack.JainMgcpStackImpl] (RestComm-akka.actor.default-dispatcher-4) Failed to locate properties file, using default values
17:12:17,430 ERROR [org.mobicents.protocols.mgcp.stack.JainMgcpStackImpl] (RestComm-akka.actor.default-dispatcher-4) java.net.BindException: Can't assign requested address
17:12:17,434 ERROR [org.mobicents.servlet.restcomm.mgcp.MediaGateway] (RestComm-akka.actor.default-dispatcher-3) Failed to find a local port 2729 to bound stack: java.lang.RuntimeException: Failed to find a local port 2729 to bound stack
	at org.mobicents.protocols.mgcp.stack.JainMgcpStackImpl.init(JainMgcpStackImpl.java:171) [mgcp-driver-3.0.2.FINAL.jar:3.0.2.FINAL]
	at org.mobicents.protocols.mgcp.stack.JainMgcpStackImpl.createProvider(JainMgcpStackImpl.java:249) [mgcp-driver-3.0.2.FINAL.jar:3.0.2.FINAL]
	at org.mobicents.servlet.restcomm.mgcp.MediaGateway.powerOn(MediaGateway.java:221) [restcomm.mgcp-7.8.0-SNAPSHOT.jar:]
	at org.mobicents.servlet.restcomm.mgcp.MediaGateway.onReceive(MediaGateway.java:267) [restcomm.mgcp-7.8.0-SNAPSHOT.jar:]
	at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:159) [akka-actor_2.10-2.1.2.jar:]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:425) [akka-actor_2.10-2.1.2.jar:]
	at akka.actor.ActorCell.invoke(ActorCell.scala:386) [akka-actor_2.10-2.1.2.jar:]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:230) [akka-actor_2.10-2.1.2.jar:]
	at akka.dispatch.Mailbox.run(Mailbox.scala:212) [akka-actor_2.10-2.1.2.jar:]
	at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:506) [akka-actor_2.10-2.1.2.jar:]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:262) [scala-library-2.10.1.jar:]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:975) [scala-library-2.10.1.jar:]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1478) [scala-library-2.10.1.jar:]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104) [scala-library-2.10.1.jar:]
```

**Comment by maria-farooq** [comment]
debugging mgcp-driver..

**Comment by maria-farooq** [comment]
basic round robin starts working with 2 media servers, just tested a simple 1234 play

**Comment by maria-farooq** [comment]
As suggested in previous comment:
`The second step would be to make the Media Server algorithm selection pluggable so that custom algorithm could be used to better assign specific calls to specific media server instances.`
But for now I will focus on https://github.com/RestComm/Restcomm-Connect/issues/1154

**Comment by maria-farooq** [comment]
@gvagenas  here are my changes so far https://github.com/RestComm/Restcomm-Connect/compare/master...maria-farooq:issue-932?expand=1

**Comment by deruelle** [comment]
Can you do a PR for that one and open  another issue for pluggable
algorithm?
Le 15 juin 2016 11:15 AM, "maria-farooq" <notifications@github.com> a
écrit :

**Comment by maria-farooq** [comment]
@deruelle @leftyb  @gvagenas for pull request, i ran test suit and found that some test cases are failing:
I think i need to look at them first, I am currently debugging them.
created https://github.com/RestComm/Restcomm-Connect/issues/1194 for pluggable algorithm

**Comment by maria-farooq** [comment]
so i last night i fixed testsuit and still some testcases are still failing. today i ran testsuit on `master` and filtered out test cases which are failing due to my changes only, here are they:
```
  ApplicationsEndpointTest.testCreateAndGetApplication:115
  SmsTest.testAliceActsAsSMSGatewayAndReceivesSMS:191
  CallLifecycleTest.testDialClientAlice:330
  CallLifecycleTest.testDialClientAlice_InvalidRCML:892
  CallLifecycleTest.testDialNumberPstn:401
  CallLifecycleTest.testDialNumberPstnBobDisconnects:535
  CallLifecycleTest.testDialNumberPstnForbidden:470
  CallLifecycleTest.testDialNumberPstnNoAnswer:687
  CallLifecycleTest.testDialNumberPstn_404NotHere:608
  CallLifecycleTest.testDialNumberPstn_500ServerInternalError:754
  CallLifecycleTest.testDialNumberPstn_BusyHere:816
```

**Comment by maria-farooq** [comment]
Hi @deruelle  meanwhile i wondered you asked to create a pull request but on this feature so far conference wont be able to mix. as each call will be landing on different media server and #1154  is still in progress

**Comment by maria-farooq** [comment]
So after debugging the reason for failure of above test cases is: in the embedded application server `restcomm.xml` is not applied properly.
i am fixing it right now

**Comment by deruelle** [comment]
@maria-farooq is this completed and ready to be merged ?

**Comment by maria-farooq** [comment]
@deruelle yes it is and can be merged. But I had discussion with @gvagenas on its merging and its better if we fix conference #1104  on multiple media-servers as well.
Apart from conference call works on this branch. and test cases are also passing.
