### ISSUE TITLE
Supervisor metrics throws error

### ISSUE THREAD

**Issue by hamsterksu** [RestComm/Restcomm-Connect#993]
Hi i have found NPE in api call

when you call `/restcomm/2012-04-24/Accounts/ACae6e420f425248d6a26948c17a9e2acf/Supervisor.json/metrics`

it throws exception 
```
java.lang.NullPointerException
	org.mobicents.servlet.restcomm.http.converter.MonitoringServiceConverter.serialize(MonitoringServiceConverter.java:62)
	org.mobicents.servlet.restcomm.http.converter.MonitoringServiceConverter.serialize(MonitoringServiceConverter.java:43)
	com.google.gson.TreeTypeAdapter.write(TreeTypeAdapter.java:70)
	com.google.gson.Gson.toJson(Gson.java:600)
	com.google.gson.Gson.toJson(Gson.java:579)
	com.google.gson.Gson.toJson(Gson.java:534)
	com.google.gson.Gson.toJson(Gson.java:514)
	org.mobicents.servlet.restcomm.http.SupervisorEndpoint.getMetrics(SupervisorEndpoint.java:153)
	org.mobicents.servlet.restcomm.http.SupservisorJsonEndpoint.getMetrics(SupservisorJsonEndpoint.java:56)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:606)
	com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
	com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
	com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
	com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
	com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
	com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
	com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1480)
	com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1411)
	com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1360)
	com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1350)
	com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416)
	com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:538)
	com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:716)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:847)
	org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)
	org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:380)
	org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
```

**Comment by hamsterksu** [comment]
also i have found another error in the server logo file

```
06:28:45,036 ERROR [org.mobicents.servlet.sip.startup.SipStandardContext] (ServerService Thread Pool -- 60) An error occured when notifying the servlet org.mobicents.servlet.restcomm.Bootstrapper of the event SERVLET_INITIALIZED: org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: java.sql.SQLException: Field 'host' doesn't have a default value
### The error may involve org.mobicents.servlet.sip.restcomm.dao.InstanceIdDao.addInstanceId-Inline
### The error occurred while setting parameters
### SQL: INSERT INTO restcomm_instance_id (instance_id, date_created, date_updated)   VALUES(?, ?, ?);
### Cause: java.sql.SQLException: Field 'host' doesn't have a default value
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:23)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:150)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:137)
	at org.mobicents.servlet.restcomm.dao.mybatis.MybatisInstanceIdDao.addInstancecId(MybatisInstanceIdDao.java:89)
	at org.mobicents.servlet.restcomm.GenerateInstanceId.instanceId(GenerateInstanceId.java:59)
	at org.mobicents.servlet.restcomm.Bootstrapper.servletInitialized(Bootstrapper.java:325)
	at org.mobicents.servlet.sip.startup.SipStandardContext.notifySipContextListeners(SipStandardContext.java:1330) [sip-servlets-as7-3.1.691.jar:3.1.691]
	at org.mobicents.servlet.sip.core.SipApplicationDispatcherImpl.addSipApplication(SipApplicationDispatcherImpl.java:574) [sip-servlets-impl-3.1.691.jar:3.1.691]
	at org.mobicents.servlet.sip.startup.SipStandardContext.start(SipStandardContext.java:380) [sip-servlets-as7-3.1.691.jar:3.1.691]
	at org.mobicents.as7.deployment.SIPWebContext.start(SIPWebContext.java:141)
	at org.jboss.as.web.deployment.WebDeploymentService.doStart(WebDeploymentService.java:156)
	at org.jboss.as.web.deployment.WebDeploymentService.access$000(WebDeploymentService.java:60)
	at org.jboss.as.web.deployment.WebDeploymentService$1.run(WebDeploymentService.java:93)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [rt.jar:1.7.0_80]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [rt.jar:1.7.0_80]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [rt.jar:1.7.0_80]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [rt.jar:1.7.0_80]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_80]
	at org.jboss.threads.JBossThread.run(JBossThread.java:122)
Caused by: java.sql.SQLException: Field 'host' doesn't have a default value
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:998)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3847)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3783)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2447)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2594)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2545)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1901)
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1193)
	at org.jboss.jca.adapters.jdbc.CachedPreparedStatement.execute(CachedPreparedStatement.java:297)
	at org.jboss.jca.adapters.jdbc.WrappedPreparedStatement.execute(WrappedPreparedStatement.java:404)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:41)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:66)
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:45)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:100)
	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:75)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:148)
	... 17 more

```

**Comment by hamsterksu** [comment]
i think it's error reason: there are no `host` parameter  
```xml
    <insert id="addInstanceId" parameterType="map">
		INSERT INTO restcomm_instance_id (instance_id, date_created, date_updated)
		VALUES(#{instance_id}, #{date_created}, #{date_updated});
	</insert>
```

https://github.com/RestComm/Restcomm-Connect/blob/master/restcomm/restcomm.application/src/main/webapp/WEB-INF/scripts/mariadb/sql/instanceId.xml#L6

**Comment by hamsterksu** [comment]
also this test script doesn't have `host` too 
https://github.com/RestComm/Restcomm-Connect/blob/master/restcomm/restcomm.dao/src/test/resources/restcomm.script

**Comment by gvagenas** [comment]
Looks like you are using an old version of Restcomm with new database schema.
The master branch of Restcomm has is correct in the "addInstanceId" check here https://github.com/RestComm/Restcomm-Connect/blob/b16d3ab7971aef7941ba8aac566c6c3527b1d9ec/restcomm/restcomm.application/src/main/webapp/WEB-INF/sql/instanceId.xml#L5-L5

and also testing locally with the latest Restcomm I cannot reproduce the issue

**Comment by hamsterksu** [comment]
@gvagenas could you open my link? - https://github.com/RestComm/Restcomm-Connect/blob/master/restcomm/restcomm.application/src/main/webapp/WEB-INF/scripts/mariadb/sql/instanceId.xml#L6 

it's mysql template. there are incorrect insert cript
