### ISSUE TITLE
RestComm need to properly handle Record failure.

### ISSUE THREAD

**Issue by leftyb** [RestComm/Restcomm-Connect#999]
WIth @hrosa advice:
RestComm always assumes MS replies with rc signal (complete) new messages but in this case, MS is failing.
RestComm should be prepared to handle record failures,
right now blindly assumes all records are processed successfully

https://github.com/RestComm/Restcomm-Connect/blob/master/restcomm/restcomm.mgcp/src/main/java/org/mobicents/servlet/restcomm/mgcp/IvrEndpoint.java#L167

**Comment by hrosa** [comment]
<img width="1548" alt="screen shot 2016-04-14 at 17 53 32" src="https://cloud.githubusercontent.com/assets/7796608/14536472/6b7ae60c-026a-11e6-9585-4ad8ad23d25c.png">

**Comment by hrosa** [comment]
https://tools.ietf.org/html/rfc2897#section-6

**Comment by hrosa** [comment]
16:41:32,313 ERROR [org.mobicents.servlet.restcomm.mgcp.IvrEndpoint] (RestComm-akka.actor.default-dispatcher-3) null: java.lang.NumberFormatException: null
       at java.lang.Integer.parseInt(Integer.java:454) [rt.jar:1.7.0_80]
       at java.lang.Integer.parseInt(Integer.java:527) [rt.jar:1.7.0_80]
       at org.mobicents.servlet.restcomm.mgcp.IvrEndpoint.notification(IvrEndpoint.java:167) [restcomm.mgcp-7.6.0.863.jar:]
       at org.mobicents.servlet.restcomm.mgcp.IvrEndpoint.onReceive(IvrEndpoint.java:125) [restcomm.mgcp-7.6.0.863.jar:]
       at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:159) [akka-actor_2.10-2.1.2.jar:]
       at akka.actor.ActorCell.receiveMessage(ActorCell.scala:425) [akka-actor_2.10-2.1.2.jar:]
       at akka.actor.ActorCell.invoke(ActorCell.scala:386) [akka-actor_2.10-2.1.2.jar:]
       at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:230) [akka-actor_2.10-2.1.2.jar:]
       at akka.dispatch.Mailbox.run(Mailbox.scala:212) [akka-actor_2.10-2.1.2.jar:]
       at akka.dispatch.ForkJoinExecutorConfigurator$MailboxExecutionTask.exec(AbstractDispatcher.scala:506) [akka-actor_2.10-2.1.2.jar:]
       at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:262) [scala-library-2.10.1.jar:]
       at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:975) [scala-library-2.10.1.jar:]
       at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1478) [scala-library-2.10.1.jar:]
       at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104) [scala-library-2.10.1.jar:]

**Comment by hrosa** [comment]
[record.pcap.zip](https://github.com/RestComm/Restcomm-Connect/files/219583/record.pcap.zip)

**Comment by hrosa** [comment]
Issue must be fixed on Media Server side, not RestComm.
Related issue https://github.com/RestComm/mediaserver/issues/115
